# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_ollyapi', [dirname(__file__)])
        except ImportError:
            import _ollyapi
            return _ollyapi
        if fp is not None:
            try:
                _mod = imp.load_module('_ollyapi', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _ollyapi = swig_import_helper()
    del swig_import_helper
else:
    import _ollyapi
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


def _swig_setattr_nondynamic_method(set):
    def set_attr(self,name,value):
        if (name == "thisown"): return self.this.own(value)
        if hasattr(self,name) or (name == "this"):
            set(self,name,value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr



def cdata(*args):
  return _ollyapi.cdata(*args)
cdata = _ollyapi.cdata

def memmove(*args):
  return _ollyapi.memmove(*args)
memmove = _ollyapi.memmove
class ulongArray(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _ollyapi.new_ulongArray(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ollyapi.delete_ulongArray
    __del__ = lambda self : None;
    def __getitem__(self, *args): return _ollyapi.ulongArray___getitem__(self, *args)
    def __setitem__(self, *args): return _ollyapi.ulongArray___setitem__(self, *args)
    def cast(self): return _ollyapi.ulongArray_cast(self)
    frompointer = staticmethod(_ollyapi.ulongArray_frompointer)
ulongArray_swigregister = _ollyapi.ulongArray_swigregister
ulongArray_swigregister(ulongArray)

def ulongArray_frompointer(*args):
  return _ollyapi.ulongArray_frompointer(*args)
ulongArray_frompointer = _ollyapi.ulongArray_frompointer

PLUGIN_VERSION = _ollyapi.PLUGIN_VERSION
TEXTLEN = _ollyapi.TEXTLEN
ARGLEN = _ollyapi.ARGLEN
USERLEN = _ollyapi.USERLEN
SHORTLEN = _ollyapi.SHORTLEN
BLACK = _ollyapi.BLACK
BLUE = _ollyapi.BLUE
GREEN = _ollyapi.GREEN
CYAN = _ollyapi.CYAN
RED = _ollyapi.RED
MAGENTA = _ollyapi.MAGENTA
BROWN = _ollyapi.BROWN
LIGHTGRAY = _ollyapi.LIGHTGRAY
DARKGRAY = _ollyapi.DARKGRAY
LIGHTBLUE = _ollyapi.LIGHTBLUE
LIGHTGREEN = _ollyapi.LIGHTGREEN
LIGHTCYAN = _ollyapi.LIGHTCYAN
LIGHTRED = _ollyapi.LIGHTRED
LIGHTMAGENTA = _ollyapi.LIGHTMAGENTA
YELLOW = _ollyapi.YELLOW
WHITE = _ollyapi.WHITE
MINT = _ollyapi.MINT
SKYBLUE = _ollyapi.SKYBLUE
IVORY = _ollyapi.IVORY
GRAY = _ollyapi.GRAY
NCOLORS = _ollyapi.NCOLORS
BKTRANSP = _ollyapi.BKTRANSP
BKBLACK = _ollyapi.BKBLACK
BKGRAY = _ollyapi.BKGRAY
BKWHITE = _ollyapi.BKWHITE
BKCYAN = _ollyapi.BKCYAN
BKGREEN = _ollyapi.BKGREEN
BKRED = _ollyapi.BKRED
BKYELLOW = _ollyapi.BKYELLOW
BLACKWHITE = _ollyapi.BLACKWHITE
BLUEGOLD = _ollyapi.BLUEGOLD
SKYWIND = _ollyapi.SKYWIND
NIGHTSTARS = _ollyapi.NIGHTSTARS
SCHEME4 = _ollyapi.SCHEME4
SCHEME5 = _ollyapi.SCHEME5
SCHEME6 = _ollyapi.SCHEME6
SCHEME7 = _ollyapi.SCHEME7
FIXEDFONT = _ollyapi.FIXEDFONT
TERMINAL6 = _ollyapi.TERMINAL6
FIXEDSYS = _ollyapi.FIXEDSYS
COURIERFONT = _ollyapi.COURIERFONT
LUCIDACONS = _ollyapi.LUCIDACONS
FONT5 = _ollyapi.FONT5
FONT6 = _ollyapi.FONT6
FONT7 = _ollyapi.FONT7
MAINFONT = _ollyapi.MAINFONT
SYSFONT = _ollyapi.SYSFONT
INFOFONT = _ollyapi.INFOFONT
ADC_DEFAULT = _ollyapi.ADC_DEFAULT
ADC_DIFFMOD = _ollyapi.ADC_DIFFMOD
ADC_NOMODNAME = _ollyapi.ADC_NOMODNAME
ADC_VALID = _ollyapi.ADC_VALID
ADC_INMODULE = _ollyapi.ADC_INMODULE
ADC_SAMEMOD = _ollyapi.ADC_SAMEMOD
ADC_SYMBOL = _ollyapi.ADC_SYMBOL
ADC_JUMP = _ollyapi.ADC_JUMP
ADC_OFFSET = _ollyapi.ADC_OFFSET
ADC_STRING = _ollyapi.ADC_STRING
ADC_ENTRY = _ollyapi.ADC_ENTRY
ADC_UPPERCASE = _ollyapi.ADC_UPPERCASE
ADC_WIDEFORM = _ollyapi.ADC_WIDEFORM
ADC_NONTRIVIAL = _ollyapi.ADC_NONTRIVIAL
ADC_DYNAMIC = _ollyapi.ADC_DYNAMIC
PLAINASCII = _ollyapi.PLAINASCII
DIACRITICAL = _ollyapi.DIACRITICAL
RAREASCII = _ollyapi.RAREASCII
MAXCMDSIZE = _ollyapi.MAXCMDSIZE
NSEQ = _ollyapi.NSEQ
NMODELS = _ollyapi.NMODELS
DIA_ASKGLOBAL = _ollyapi.DIA_ASKGLOBAL
DIA_HEXONLY = _ollyapi.DIA_HEXONLY
DIA_ALIGNED = _ollyapi.DIA_ALIGNED
DIA_DEFHEX = _ollyapi.DIA_DEFHEX
DIA_DEFASCII = _ollyapi.DIA_DEFASCII
DIA_DEFUNICODE = _ollyapi.DIA_DEFUNICODE
DIA_SEARCH = _ollyapi.DIA_SEARCH
DIA_HISTORY = _ollyapi.DIA_HISTORY
ANIMATE_OFF = _ollyapi.ANIMATE_OFF
ANIMATE_IN = _ollyapi.ANIMATE_IN
ANIMATE_OVER = _ollyapi.ANIMATE_OVER
ANIMATE_RET = _ollyapi.ANIMATE_RET
ANIMATE_SKPRET = _ollyapi.ANIMATE_SKPRET
ANIMATE_USER = _ollyapi.ANIMATE_USER
ANIMATE_TRIN = _ollyapi.ANIMATE_TRIN
ANIMATE_TROVER = _ollyapi.ANIMATE_TROVER
ANIMATE_STOP = _ollyapi.ANIMATE_STOP
class t_hexstr(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    n = _swig_property(_ollyapi.t_hexstr_n_get, _ollyapi.t_hexstr_n_set)
    data = _swig_property(_ollyapi.t_hexstr_data_get, _ollyapi.t_hexstr_data_set)
    mask = _swig_property(_ollyapi.t_hexstr_mask_get, _ollyapi.t_hexstr_mask_set)
    def __init__(self): 
        this = _ollyapi.new_t_hexstr()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ollyapi.delete_t_hexstr
    __del__ = lambda self : None;
t_hexstr_swigregister = _ollyapi.t_hexstr_swigregister
t_hexstr_swigregister(t_hexstr)

class t_asmmodel(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    code = _swig_property(_ollyapi.t_asmmodel_code_get, _ollyapi.t_asmmodel_code_set)
    mask = _swig_property(_ollyapi.t_asmmodel_mask_get, _ollyapi.t_asmmodel_mask_set)
    length = _swig_property(_ollyapi.t_asmmodel_length_get, _ollyapi.t_asmmodel_length_set)
    jmpsize = _swig_property(_ollyapi.t_asmmodel_jmpsize_get, _ollyapi.t_asmmodel_jmpsize_set)
    jmpoffset = _swig_property(_ollyapi.t_asmmodel_jmpoffset_get, _ollyapi.t_asmmodel_jmpoffset_set)
    jmppos = _swig_property(_ollyapi.t_asmmodel_jmppos_get, _ollyapi.t_asmmodel_jmppos_set)
    def __init__(self): 
        this = _ollyapi.new_t_asmmodel()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ollyapi.delete_t_asmmodel
    __del__ = lambda self : None;
t_asmmodel_swigregister = _ollyapi.t_asmmodel_swigregister
t_asmmodel_swigregister(t_asmmodel)

class t_extmodel(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    code = _swig_property(_ollyapi.t_extmodel_code_get, _ollyapi.t_extmodel_code_set)
    mask = _swig_property(_ollyapi.t_extmodel_mask_get, _ollyapi.t_extmodel_mask_set)
    length = _swig_property(_ollyapi.t_extmodel_length_get, _ollyapi.t_extmodel_length_set)
    jmpsize = _swig_property(_ollyapi.t_extmodel_jmpsize_get, _ollyapi.t_extmodel_jmpsize_set)
    jmpoffset = _swig_property(_ollyapi.t_extmodel_jmpoffset_get, _ollyapi.t_extmodel_jmpoffset_set)
    jmppos = _swig_property(_ollyapi.t_extmodel_jmppos_get, _ollyapi.t_extmodel_jmppos_set)
    isany = _swig_property(_ollyapi.t_extmodel_isany_get, _ollyapi.t_extmodel_isany_set)
    cmdoffset = _swig_property(_ollyapi.t_extmodel_cmdoffset_get, _ollyapi.t_extmodel_cmdoffset_set)
    ramask = _swig_property(_ollyapi.t_extmodel_ramask_get, _ollyapi.t_extmodel_ramask_set)
    rbmask = _swig_property(_ollyapi.t_extmodel_rbmask_get, _ollyapi.t_extmodel_rbmask_set)
    def __init__(self): 
        this = _ollyapi.new_t_extmodel()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ollyapi.delete_t_extmodel
    __del__ = lambda self : None;
t_extmodel_swigregister = _ollyapi.t_extmodel_swigregister
t_extmodel_swigregister(t_extmodel)

NBAR = _ollyapi.NBAR
BAR_PRESSED = _ollyapi.BAR_PRESSED
BAR_DISABLED = _ollyapi.BAR_DISABLED
BAR_NOSORT = _ollyapi.BAR_NOSORT
BAR_NORESIZE = _ollyapi.BAR_NORESIZE
BAR_BUTTON = _ollyapi.BAR_BUTTON
BAR_SHIFTSEL = _ollyapi.BAR_SHIFTSEL
CAPT_FREE = _ollyapi.CAPT_FREE
TABLE_DIR = _ollyapi.TABLE_DIR
TABLE_COPYMENU = _ollyapi.TABLE_COPYMENU
TABLE_SORTMENU = _ollyapi.TABLE_SORTMENU
TABLE_APPMENU = _ollyapi.TABLE_APPMENU
TABLE_WIDECOL = _ollyapi.TABLE_WIDECOL
TABLE_USERAPP = _ollyapi.TABLE_USERAPP
TABLE_USERDEF = _ollyapi.TABLE_USERDEF
TABLE_NOHSCR = _ollyapi.TABLE_NOHSCR
TABLE_SAVEPOS = _ollyapi.TABLE_SAVEPOS
TABLE_CPU = _ollyapi.TABLE_CPU
TABLE_FASTSEL = _ollyapi.TABLE_FASTSEL
TABLE_COLSEL = _ollyapi.TABLE_COLSEL
TABLE_SAVEAPP = _ollyapi.TABLE_SAVEAPP
TABLE_HILMENU = _ollyapi.TABLE_HILMENU
TABLE_ONTOP = _ollyapi.TABLE_ONTOP
DRAW_NORMAL = _ollyapi.DRAW_NORMAL
DRAW_GRAY = _ollyapi.DRAW_GRAY
DRAW_HILITE = _ollyapi.DRAW_HILITE
DRAW_UL = _ollyapi.DRAW_UL
DRAW_SELECT = _ollyapi.DRAW_SELECT
DRAW_EIP = _ollyapi.DRAW_EIP
DRAW_BREAK = _ollyapi.DRAW_BREAK
DRAW_GRAPH = _ollyapi.DRAW_GRAPH
DRAW_DIRECT = _ollyapi.DRAW_DIRECT
DRAW_MASK = _ollyapi.DRAW_MASK
DRAW_EXTSEL = _ollyapi.DRAW_EXTSEL
DRAW_UNICODE = _ollyapi.DRAW_UNICODE
DRAW_TOP = _ollyapi.DRAW_TOP
DRAW_BOTTOM = _ollyapi.DRAW_BOTTOM
D_SPACE = _ollyapi.D_SPACE
D_SEP = _ollyapi.D_SEP
D_BEGIN = _ollyapi.D_BEGIN
D_BODY = _ollyapi.D_BODY
D_ENTRY = _ollyapi.D_ENTRY
D_LEAF = _ollyapi.D_LEAF
D_END = _ollyapi.D_END
D_SINGLE = _ollyapi.D_SINGLE
D_ENDBEG = _ollyapi.D_ENDBEG
D_POINT = _ollyapi.D_POINT
D_JMPUP = _ollyapi.D_JMPUP
D_JMPOUT = _ollyapi.D_JMPOUT
D_JMPDN = _ollyapi.D_JMPDN
D_PATHUP = _ollyapi.D_PATHUP
D_GRAYUP = _ollyapi.D_GRAYUP
D_PATH = _ollyapi.D_PATH
D_GRAYPATH = _ollyapi.D_GRAYPATH
D_PATHDN = _ollyapi.D_PATHDN
D_GRAYDN = _ollyapi.D_GRAYDN
D_PATHUPEND = _ollyapi.D_PATHUPEND
D_GRAYUPEND = _ollyapi.D_GRAYUPEND
D_PATHDNEND = _ollyapi.D_PATHDNEND
D_GRAYDNEND = _ollyapi.D_GRAYDNEND
D_SWTOP = _ollyapi.D_SWTOP
D_SWBODY = _ollyapi.D_SWBODY
D_CASE = _ollyapi.D_CASE
D_LASTCASE = _ollyapi.D_LASTCASE
TY_NEW = _ollyapi.TY_NEW
TY_CONFIRMED = _ollyapi.TY_CONFIRMED
TY_MAIN = _ollyapi.TY_MAIN
TY_INVALID = _ollyapi.TY_INVALID
TY_SELECTED = _ollyapi.TY_SELECTED
TY_REPORTED = _ollyapi.TY_REPORTED
TY_REFERENCE = _ollyapi.TY_REFERENCE
TY_ORIGIN = _ollyapi.TY_ORIGIN
TY_STOPAN = _ollyapi.TY_STOPAN
TY_SET = _ollyapi.TY_SET
TY_ACTIVE = _ollyapi.TY_ACTIVE
TY_DISABLED = _ollyapi.TY_DISABLED
TY_ONESHOT = _ollyapi.TY_ONESHOT
TY_TEMP = _ollyapi.TY_TEMP
TY_KEEPCODE = _ollyapi.TY_KEEPCODE
TY_KEEPCOND = _ollyapi.TY_KEEPCOND
TY_NOUPDATE = _ollyapi.TY_NOUPDATE
TY_RTRACE = _ollyapi.TY_RTRACE
TY_EXPORT = _ollyapi.TY_EXPORT
TY_IMPORT = _ollyapi.TY_IMPORT
TY_LIBRARY = _ollyapi.TY_LIBRARY
TY_LABEL = _ollyapi.TY_LABEL
TY_ANYNAME = _ollyapi.TY_ANYNAME
TY_KNOWN = _ollyapi.TY_KNOWN
TY_DEFHEAP = _ollyapi.TY_DEFHEAP
TY_HEAP = _ollyapi.TY_HEAP
TY_SFX = _ollyapi.TY_SFX
TY_CODE = _ollyapi.TY_CODE
TY_DATA = _ollyapi.TY_DATA
TY_IMPDATA = _ollyapi.TY_IMPDATA
TY_EXPDATA = _ollyapi.TY_EXPDATA
TY_RSRC = _ollyapi.TY_RSRC
TY_RELOC = _ollyapi.TY_RELOC
TY_STACK = _ollyapi.TY_STACK
TY_THREAD = _ollyapi.TY_THREAD
TY_HEADER = _ollyapi.TY_HEADER
TY_ANYMEM = _ollyapi.TY_ANYMEM
TY_GUARDED = _ollyapi.TY_GUARDED
TY_PURE = _ollyapi.TY_PURE
TY_PASCAL = _ollyapi.TY_PASCAL
TY_C = _ollyapi.TY_C
TY_NOTENTRY = _ollyapi.TY_NOTENTRY
TY_CHARSW = _ollyapi.TY_CHARSW
TY_WMSW = _ollyapi.TY_WMSW
TY_EXCEPTSW = _ollyapi.TY_EXCEPTSW
TY_RELIABLE = _ollyapi.TY_RELIABLE
TY_GUESSED = _ollyapi.TY_GUESSED
TY_BELONGS = _ollyapi.TY_BELONGS
TY_RECURSIVE = _ollyapi.TY_RECURSIVE
TY_TERMINAL = _ollyapi.TY_TERMINAL
TY_SYSTEM = _ollyapi.TY_SYSTEM
TY_DIRECT = _ollyapi.TY_DIRECT
TY_NODATA = _ollyapi.TY_NODATA
TY_DUMMY = _ollyapi.TY_DUMMY
TY_NOSIDE = _ollyapi.TY_NOSIDE
class t_scheme(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    name = _swig_property(_ollyapi.t_scheme_name_get, _ollyapi.t_scheme_name_set)
    textcolor = _swig_property(_ollyapi.t_scheme_textcolor_get, _ollyapi.t_scheme_textcolor_set)
    hitextcolor = _swig_property(_ollyapi.t_scheme_hitextcolor_get, _ollyapi.t_scheme_hitextcolor_set)
    lowcolor = _swig_property(_ollyapi.t_scheme_lowcolor_get, _ollyapi.t_scheme_lowcolor_set)
    bkcolor = _swig_property(_ollyapi.t_scheme_bkcolor_get, _ollyapi.t_scheme_bkcolor_set)
    selbkcolor = _swig_property(_ollyapi.t_scheme_selbkcolor_get, _ollyapi.t_scheme_selbkcolor_set)
    linecolor = _swig_property(_ollyapi.t_scheme_linecolor_get, _ollyapi.t_scheme_linecolor_set)
    auxcolor = _swig_property(_ollyapi.t_scheme_auxcolor_get, _ollyapi.t_scheme_auxcolor_set)
    condbkcolor = _swig_property(_ollyapi.t_scheme_condbkcolor_get, _ollyapi.t_scheme_condbkcolor_set)
    def __init__(self): 
        this = _ollyapi.new_t_scheme()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ollyapi.delete_t_scheme
    __del__ = lambda self : None;
t_scheme_swigregister = _ollyapi.t_scheme_swigregister
t_scheme_swigregister(t_scheme)

class t_schemeopt(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    name = _swig_property(_ollyapi.t_schemeopt_name_get, _ollyapi.t_schemeopt_name_set)
    color = _swig_property(_ollyapi.t_schemeopt_color_get, _ollyapi.t_schemeopt_color_set)
    def __init__(self): 
        this = _ollyapi.new_t_schemeopt()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ollyapi.delete_t_schemeopt
    __del__ = lambda self : None;
t_schemeopt_swigregister = _ollyapi.t_schemeopt_swigregister
t_schemeopt_swigregister(t_schemeopt)

class t_bar(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    nbar = _swig_property(_ollyapi.t_bar_nbar_get, _ollyapi.t_bar_nbar_set)
    font = _swig_property(_ollyapi.t_bar_font_get, _ollyapi.t_bar_font_set)
    dx = _swig_property(_ollyapi.t_bar_dx_get, _ollyapi.t_bar_dx_set)
    defdx = _swig_property(_ollyapi.t_bar_defdx_get, _ollyapi.t_bar_defdx_set)
    name = _swig_property(_ollyapi.t_bar_name_get, _ollyapi.t_bar_name_set)
    mode = _swig_property(_ollyapi.t_bar_mode_get, _ollyapi.t_bar_mode_set)
    captured = _swig_property(_ollyapi.t_bar_captured_get, _ollyapi.t_bar_captured_set)
    active = _swig_property(_ollyapi.t_bar_active_get, _ollyapi.t_bar_active_set)
    prevx = _swig_property(_ollyapi.t_bar_prevx_get, _ollyapi.t_bar_prevx_set)
    def __init__(self): 
        this = _ollyapi.new_t_bar()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ollyapi.delete_t_bar
    __del__ = lambda self : None;
t_bar_swigregister = _ollyapi.t_bar_swigregister
t_bar_swigregister(t_bar)

class t_sortheader(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    addr = _swig_property(_ollyapi.t_sortheader_addr_get, _ollyapi.t_sortheader_addr_set)
    size = _swig_property(_ollyapi.t_sortheader_size_get, _ollyapi.t_sortheader_size_set)
    type = _swig_property(_ollyapi.t_sortheader_type_get, _ollyapi.t_sortheader_type_set)
    def __init__(self): 
        this = _ollyapi.new_t_sortheader()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ollyapi.delete_t_sortheader
    __del__ = lambda self : None;
t_sortheader_swigregister = _ollyapi.t_sortheader_swigregister
t_sortheader_swigregister(t_sortheader)

class t_sorted(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    name = _swig_property(_ollyapi.t_sorted_name_get, _ollyapi.t_sorted_name_set)
    n = _swig_property(_ollyapi.t_sorted_n_get, _ollyapi.t_sorted_n_set)
    nmax = _swig_property(_ollyapi.t_sorted_nmax_get, _ollyapi.t_sorted_nmax_set)
    selected = _swig_property(_ollyapi.t_sorted_selected_get, _ollyapi.t_sorted_selected_set)
    seladdr = _swig_property(_ollyapi.t_sorted_seladdr_get, _ollyapi.t_sorted_seladdr_set)
    itemsize = _swig_property(_ollyapi.t_sorted_itemsize_get, _ollyapi.t_sorted_itemsize_set)
    version = _swig_property(_ollyapi.t_sorted_version_get, _ollyapi.t_sorted_version_set)
    data = _swig_property(_ollyapi.t_sorted_data_get, _ollyapi.t_sorted_data_set)
    sortfunc = _swig_property(_ollyapi.t_sorted_sortfunc_get, _ollyapi.t_sorted_sortfunc_set)
    destfunc = _swig_property(_ollyapi.t_sorted_destfunc_get, _ollyapi.t_sorted_destfunc_set)
    sort = _swig_property(_ollyapi.t_sorted_sort_get, _ollyapi.t_sorted_sort_set)
    sorted = _swig_property(_ollyapi.t_sorted_sorted_get, _ollyapi.t_sorted_sorted_set)
    index = _swig_property(_ollyapi.t_sorted_index_get, _ollyapi.t_sorted_index_set)
    suppresserr = _swig_property(_ollyapi.t_sorted_suppresserr_get, _ollyapi.t_sorted_suppresserr_set)
    def __init__(self): 
        this = _ollyapi.new_t_sorted()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ollyapi.delete_t_sorted
    __del__ = lambda self : None;
t_sorted_swigregister = _ollyapi.t_sorted_swigregister
t_sorted_swigregister(t_sorted)

class t_table(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    hw = _swig_property(_ollyapi.t_table_hw_get, _ollyapi.t_table_hw_set)
    data = _swig_property(_ollyapi.t_table_data_get, _ollyapi.t_table_data_set)
    bar = _swig_property(_ollyapi.t_table_bar_get, _ollyapi.t_table_bar_set)
    showbar = _swig_property(_ollyapi.t_table_showbar_get, _ollyapi.t_table_showbar_set)
    hscroll = _swig_property(_ollyapi.t_table_hscroll_get, _ollyapi.t_table_hscroll_set)
    colsel = _swig_property(_ollyapi.t_table_colsel_get, _ollyapi.t_table_colsel_set)
    mode = _swig_property(_ollyapi.t_table_mode_get, _ollyapi.t_table_mode_set)
    font = _swig_property(_ollyapi.t_table_font_get, _ollyapi.t_table_font_set)
    scheme = _swig_property(_ollyapi.t_table_scheme_get, _ollyapi.t_table_scheme_set)
    hilite = _swig_property(_ollyapi.t_table_hilite_get, _ollyapi.t_table_hilite_set)
    offset = _swig_property(_ollyapi.t_table_offset_get, _ollyapi.t_table_offset_set)
    xshift = _swig_property(_ollyapi.t_table_xshift_get, _ollyapi.t_table_xshift_set)
    drawfunc = _swig_property(_ollyapi.t_table_drawfunc_get, _ollyapi.t_table_drawfunc_set)
    def __init__(self): 
        this = _ollyapi.new_t_table()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ollyapi.delete_t_table
    __del__ = lambda self : None;
t_table_swigregister = _ollyapi.t_table_swigregister
t_table_swigregister(t_table)

NM_NONAME = _ollyapi.NM_NONAME
NM_ANYNAME = _ollyapi.NM_ANYNAME
NM_PLUGCMD = _ollyapi.NM_PLUGCMD
NM_LABEL = _ollyapi.NM_LABEL
NM_EXPORT = _ollyapi.NM_EXPORT
NM_IMPORT = _ollyapi.NM_IMPORT
NM_LIBRARY = _ollyapi.NM_LIBRARY
NM_CONST = _ollyapi.NM_CONST
NM_COMMENT = _ollyapi.NM_COMMENT
NM_LIBCOMM = _ollyapi.NM_LIBCOMM
NM_BREAK = _ollyapi.NM_BREAK
NM_ARG = _ollyapi.NM_ARG
NM_ANALYSE = _ollyapi.NM_ANALYSE
NM_BREAKEXPR = _ollyapi.NM_BREAKEXPR
NM_BREAKEXPL = _ollyapi.NM_BREAKEXPL
NM_ASSUME = _ollyapi.NM_ASSUME
NM_STRUCT = _ollyapi.NM_STRUCT
NM_CASE = _ollyapi.NM_CASE
NM_INSPECT = _ollyapi.NM_INSPECT
NM_WATCH = _ollyapi.NM_WATCH
NM_ASM = _ollyapi.NM_ASM
NM_FINDASM = _ollyapi.NM_FINDASM
NM_LASTWATCH = _ollyapi.NM_LASTWATCH
NM_SOURCE = _ollyapi.NM_SOURCE
NM_REFTXT = _ollyapi.NM_REFTXT
NM_GOTO = _ollyapi.NM_GOTO
NM_GOTODUMP = _ollyapi.NM_GOTODUMP
NM_TRPAUSE = _ollyapi.NM_TRPAUSE
NM_IMCALL = _ollyapi.NM_IMCALL
NMHISTORY = _ollyapi.NMHISTORY
REG_EAX = _ollyapi.REG_EAX
REG_ECX = _ollyapi.REG_ECX
REG_EDX = _ollyapi.REG_EDX
REG_EBX = _ollyapi.REG_EBX
REG_ESP = _ollyapi.REG_ESP
REG_EBP = _ollyapi.REG_EBP
REG_ESI = _ollyapi.REG_ESI
REG_EDI = _ollyapi.REG_EDI
SEG_UNDEF = _ollyapi.SEG_UNDEF
SEG_ES = _ollyapi.SEG_ES
SEG_CS = _ollyapi.SEG_CS
SEG_SS = _ollyapi.SEG_SS
SEG_DS = _ollyapi.SEG_DS
SEG_FS = _ollyapi.SEG_FS
SEG_GS = _ollyapi.SEG_GS
RS_NONE = _ollyapi.RS_NONE
RS_INT = _ollyapi.RS_INT
RS_EIP = _ollyapi.RS_EIP
RS_FLG = _ollyapi.RS_FLG
RS_SEG = _ollyapi.RS_SEG
RS_EFL = _ollyapi.RS_EFL
RS_TAG = _ollyapi.RS_TAG
RS_FPU = _ollyapi.RS_FPU
RS_FST = _ollyapi.RS_FST
RS_FCO = _ollyapi.RS_FCO
RS_FER = _ollyapi.RS_FER
RS_FCW = _ollyapi.RS_FCW
RS_FPR = _ollyapi.RS_FPR
RS_FEM = _ollyapi.RS_FEM
RS_MMX = _ollyapi.RS_MMX
RS_3DN = _ollyapi.RS_3DN
RS_SSE = _ollyapi.RS_SSE
RS_CSR = _ollyapi.RS_CSR
RS_CSB = _ollyapi.RS_CSB
RS_CPR = _ollyapi.RS_CPR
RS_ERR = _ollyapi.RS_ERR
RS_GROUP = _ollyapi.RS_GROUP
RS_INDEX = _ollyapi.RS_INDEX
NREGSTACK = _ollyapi.NREGSTACK
MAXCALSIZE = _ollyapi.MAXCALSIZE
INT3 = _ollyapi.INT3
NOP = _ollyapi.NOP
TRAPFLAG = _ollyapi.TRAPFLAG
C_TYPEMASK = _ollyapi.C_TYPEMASK
C_CMD = _ollyapi.C_CMD
C_PSH = _ollyapi.C_PSH
C_POP = _ollyapi.C_POP
C_MMX = _ollyapi.C_MMX
C_FLT = _ollyapi.C_FLT
C_JMP = _ollyapi.C_JMP
C_JMC = _ollyapi.C_JMC
C_CAL = _ollyapi.C_CAL
C_RET = _ollyapi.C_RET
C_FLG = _ollyapi.C_FLG
C_RTF = _ollyapi.C_RTF
C_REP = _ollyapi.C_REP
C_PRI = _ollyapi.C_PRI
C_SSE = _ollyapi.C_SSE
C_NOW = _ollyapi.C_NOW
C_BAD = _ollyapi.C_BAD
C_RARE = _ollyapi.C_RARE
C_SIZEMASK = _ollyapi.C_SIZEMASK
C_EXPL = _ollyapi.C_EXPL
C_DANGER95 = _ollyapi.C_DANGER95
C_DANGER = _ollyapi.C_DANGER
C_DANGERLOCK = _ollyapi.C_DANGERLOCK
DEC_TYPEMASK = _ollyapi.DEC_TYPEMASK
DEC_UNKNOWN = _ollyapi.DEC_UNKNOWN
DEC_BYTE = _ollyapi.DEC_BYTE
DEC_WORD = _ollyapi.DEC_WORD
DEC_NEXTDATA = _ollyapi.DEC_NEXTDATA
DEC_DWORD = _ollyapi.DEC_DWORD
DEC_FLOAT4 = _ollyapi.DEC_FLOAT4
DEC_FWORD = _ollyapi.DEC_FWORD
DEC_FLOAT8 = _ollyapi.DEC_FLOAT8
DEC_QWORD = _ollyapi.DEC_QWORD
DEC_FLOAT10 = _ollyapi.DEC_FLOAT10
DEC_TBYTE = _ollyapi.DEC_TBYTE
DEC_STRING = _ollyapi.DEC_STRING
DEC_UNICODE = _ollyapi.DEC_UNICODE
DEC_3DNOW = _ollyapi.DEC_3DNOW
DEC_SSE = _ollyapi.DEC_SSE
DEC_TEXT = _ollyapi.DEC_TEXT
DEC_BYTESW = _ollyapi.DEC_BYTESW
DEC_NEXTCODE = _ollyapi.DEC_NEXTCODE
DEC_COMMAND = _ollyapi.DEC_COMMAND
DEC_JMPDEST = _ollyapi.DEC_JMPDEST
DEC_CALLDEST = _ollyapi.DEC_CALLDEST
DEC_PROCMASK = _ollyapi.DEC_PROCMASK
DEC_PROC = _ollyapi.DEC_PROC
DEC_PBODY = _ollyapi.DEC_PBODY
DEC_PEND = _ollyapi.DEC_PEND
DEC_CHECKED = _ollyapi.DEC_CHECKED
DEC_SIGNED = _ollyapi.DEC_SIGNED
DISASM_SIZE = _ollyapi.DISASM_SIZE
DISASM_DATA = _ollyapi.DISASM_DATA
DISASM_TRACE = _ollyapi.DISASM_TRACE
DISASM_FILE = _ollyapi.DISASM_FILE
DISASM_CODE = _ollyapi.DISASM_CODE
DISASM_ALL = _ollyapi.DISASM_ALL
DISASM_RTRACE = _ollyapi.DISASM_RTRACE
DISASM_MODE = _ollyapi.DISASM_MODE
DISASM_HILITE = _ollyapi.DISASM_HILITE
DISASM_HLSHIFT = _ollyapi.DISASM_HLSHIFT
DAW_FARADDR = _ollyapi.DAW_FARADDR
DAW_SEGMENT = _ollyapi.DAW_SEGMENT
DAW_PRIV = _ollyapi.DAW_PRIV
DAW_IO = _ollyapi.DAW_IO
DAW_SHIFT = _ollyapi.DAW_SHIFT
DAW_PREFIX = _ollyapi.DAW_PREFIX
DAW_LOCK = _ollyapi.DAW_LOCK
DAW_STACK = _ollyapi.DAW_STACK
DAW_DANGER95 = _ollyapi.DAW_DANGER95
DAW_DANGEROUS = _ollyapi.DAW_DANGEROUS
RST_INVALID = _ollyapi.RST_INVALID
RST_VALUE = _ollyapi.RST_VALUE
RST_VFIXUP = _ollyapi.RST_VFIXUP
RST_INDIRECT = _ollyapi.RST_INDIRECT
class t_reg(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    modified = _swig_property(_ollyapi.t_reg_modified_get, _ollyapi.t_reg_modified_set)
    modifiedbyuser = _swig_property(_ollyapi.t_reg_modifiedbyuser_get, _ollyapi.t_reg_modifiedbyuser_set)
    singlestep = _swig_property(_ollyapi.t_reg_singlestep_get, _ollyapi.t_reg_singlestep_set)
    r = _swig_property(_ollyapi.t_reg_r_get, _ollyapi.t_reg_r_set)
    ip = _swig_property(_ollyapi.t_reg_ip_get, _ollyapi.t_reg_ip_set)
    flags = _swig_property(_ollyapi.t_reg_flags_get, _ollyapi.t_reg_flags_set)
    top = _swig_property(_ollyapi.t_reg_top_get, _ollyapi.t_reg_top_set)
    f = _swig_property(_ollyapi.t_reg_f_get, _ollyapi.t_reg_f_set)
    tag = _swig_property(_ollyapi.t_reg_tag_get, _ollyapi.t_reg_tag_set)
    fst = _swig_property(_ollyapi.t_reg_fst_get, _ollyapi.t_reg_fst_set)
    fcw = _swig_property(_ollyapi.t_reg_fcw_get, _ollyapi.t_reg_fcw_set)
    s = _swig_property(_ollyapi.t_reg_s_get, _ollyapi.t_reg_s_set)
    base = _swig_property(_ollyapi.t_reg_base_get, _ollyapi.t_reg_base_set)
    limit = _swig_property(_ollyapi.t_reg_limit_get, _ollyapi.t_reg_limit_set)
    big = _swig_property(_ollyapi.t_reg_big_get, _ollyapi.t_reg_big_set)
    dr6 = _swig_property(_ollyapi.t_reg_dr6_get, _ollyapi.t_reg_dr6_set)
    threadid = _swig_property(_ollyapi.t_reg_threadid_get, _ollyapi.t_reg_threadid_set)
    lasterror = _swig_property(_ollyapi.t_reg_lasterror_get, _ollyapi.t_reg_lasterror_set)
    ssevalid = _swig_property(_ollyapi.t_reg_ssevalid_get, _ollyapi.t_reg_ssevalid_set)
    ssemodified = _swig_property(_ollyapi.t_reg_ssemodified_get, _ollyapi.t_reg_ssemodified_set)
    ssereg = _swig_property(_ollyapi.t_reg_ssereg_get, _ollyapi.t_reg_ssereg_set)
    mxcsr = _swig_property(_ollyapi.t_reg_mxcsr_get, _ollyapi.t_reg_mxcsr_set)
    selected = _swig_property(_ollyapi.t_reg_selected_get, _ollyapi.t_reg_selected_set)
    drlin = _swig_property(_ollyapi.t_reg_drlin_get, _ollyapi.t_reg_drlin_set)
    dr7 = _swig_property(_ollyapi.t_reg_dr7_get, _ollyapi.t_reg_dr7_set)
    def __init__(self): 
        this = _ollyapi.new_t_reg()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ollyapi.delete_t_reg
    __del__ = lambda self : None;
t_reg_swigregister = _ollyapi.t_reg_swigregister
t_reg_swigregister(t_reg)

class t_operand(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    optype = _swig_property(_ollyapi.t_operand_optype_get, _ollyapi.t_operand_optype_set)
    opsize = _swig_property(_ollyapi.t_operand_opsize_get, _ollyapi.t_operand_opsize_set)
    regscale = _swig_property(_ollyapi.t_operand_regscale_get, _ollyapi.t_operand_regscale_set)
    seg = _swig_property(_ollyapi.t_operand_seg_get, _ollyapi.t_operand_seg_set)
    opconst = _swig_property(_ollyapi.t_operand_opconst_get, _ollyapi.t_operand_opconst_set)
    def __init__(self): 
        this = _ollyapi.new_t_operand()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ollyapi.delete_t_operand
    __del__ = lambda self : None;
t_operand_swigregister = _ollyapi.t_operand_swigregister
t_operand_swigregister(t_operand)

class t_disasm(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    ip = _swig_property(_ollyapi.t_disasm_ip_get, _ollyapi.t_disasm_ip_set)
    dump = _swig_property(_ollyapi.t_disasm_dump_get, _ollyapi.t_disasm_dump_set)
    result = _swig_property(_ollyapi.t_disasm_result_get, _ollyapi.t_disasm_result_set)
    comment = _swig_property(_ollyapi.t_disasm_comment_get, _ollyapi.t_disasm_comment_set)
    opinfo = _swig_property(_ollyapi.t_disasm_opinfo_get, _ollyapi.t_disasm_opinfo_set)
    cmdtype = _swig_property(_ollyapi.t_disasm_cmdtype_get, _ollyapi.t_disasm_cmdtype_set)
    memtype = _swig_property(_ollyapi.t_disasm_memtype_get, _ollyapi.t_disasm_memtype_set)
    nprefix = _swig_property(_ollyapi.t_disasm_nprefix_get, _ollyapi.t_disasm_nprefix_set)
    indexed = _swig_property(_ollyapi.t_disasm_indexed_get, _ollyapi.t_disasm_indexed_set)
    jmpconst = _swig_property(_ollyapi.t_disasm_jmpconst_get, _ollyapi.t_disasm_jmpconst_set)
    jmptable = _swig_property(_ollyapi.t_disasm_jmptable_get, _ollyapi.t_disasm_jmptable_set)
    adrconst = _swig_property(_ollyapi.t_disasm_adrconst_get, _ollyapi.t_disasm_adrconst_set)
    immconst = _swig_property(_ollyapi.t_disasm_immconst_get, _ollyapi.t_disasm_immconst_set)
    zeroconst = _swig_property(_ollyapi.t_disasm_zeroconst_get, _ollyapi.t_disasm_zeroconst_set)
    fixupoffset = _swig_property(_ollyapi.t_disasm_fixupoffset_get, _ollyapi.t_disasm_fixupoffset_set)
    fixupsize = _swig_property(_ollyapi.t_disasm_fixupsize_get, _ollyapi.t_disasm_fixupsize_set)
    jmpaddr = _swig_property(_ollyapi.t_disasm_jmpaddr_get, _ollyapi.t_disasm_jmpaddr_set)
    condition = _swig_property(_ollyapi.t_disasm_condition_get, _ollyapi.t_disasm_condition_set)
    error = _swig_property(_ollyapi.t_disasm_error_get, _ollyapi.t_disasm_error_set)
    warnings = _swig_property(_ollyapi.t_disasm_warnings_get, _ollyapi.t_disasm_warnings_set)
    optype = _swig_property(_ollyapi.t_disasm_optype_get, _ollyapi.t_disasm_optype_set)
    opsize = _swig_property(_ollyapi.t_disasm_opsize_get, _ollyapi.t_disasm_opsize_set)
    opgood = _swig_property(_ollyapi.t_disasm_opgood_get, _ollyapi.t_disasm_opgood_set)
    opaddr = _swig_property(_ollyapi.t_disasm_opaddr_get, _ollyapi.t_disasm_opaddr_set)
    opdata = _swig_property(_ollyapi.t_disasm_opdata_get, _ollyapi.t_disasm_opdata_set)
    op = _swig_property(_ollyapi.t_disasm_op_get, _ollyapi.t_disasm_op_set)
    regdata = _swig_property(_ollyapi.t_disasm_regdata_get, _ollyapi.t_disasm_regdata_set)
    regstatus = _swig_property(_ollyapi.t_disasm_regstatus_get, _ollyapi.t_disasm_regstatus_set)
    addrdata = _swig_property(_ollyapi.t_disasm_addrdata_get, _ollyapi.t_disasm_addrdata_set)
    addrstatus = _swig_property(_ollyapi.t_disasm_addrstatus_get, _ollyapi.t_disasm_addrstatus_set)
    regstack = _swig_property(_ollyapi.t_disasm_regstack_get, _ollyapi.t_disasm_regstack_set)
    rststatus = _swig_property(_ollyapi.t_disasm_rststatus_get, _ollyapi.t_disasm_rststatus_set)
    nregstack = _swig_property(_ollyapi.t_disasm_nregstack_get, _ollyapi.t_disasm_nregstack_set)
    reserved = _swig_property(_ollyapi.t_disasm_reserved_get, _ollyapi.t_disasm_reserved_set)
    def __init__(self): 
        this = _ollyapi.new_t_disasm()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ollyapi.delete_t_disasm
    __del__ = lambda self : None;
t_disasm_swigregister = _ollyapi.t_disasm_swigregister
t_disasm_swigregister(t_disasm)

class t_result(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    type = _swig_property(_ollyapi.t_result_type_get, _ollyapi.t_result_type_set)
    dtype = _swig_property(_ollyapi.t_result_dtype_get, _ollyapi.t_result_dtype_set)
    u = _swig_property(_ollyapi.t_result_u_get)
    value = _swig_property(_ollyapi.t_result_value_get, _ollyapi.t_result_value_set)
    wvalue = _swig_property(_ollyapi.t_result_wvalue_get, _ollyapi.t_result_wvalue_set)
    lvaddr = _swig_property(_ollyapi.t_result_lvaddr_get, _ollyapi.t_result_lvaddr_set)
    def __init__(self): 
        this = _ollyapi.new_t_result()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ollyapi.delete_t_result
    __del__ = lambda self : None;
t_result_swigregister = _ollyapi.t_result_swigregister
t_result_swigregister(t_result)

class t_result_u(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    data = _swig_property(_ollyapi.t_result_u_data_get, _ollyapi.t_result_u_data_set)
    u = _swig_property(_ollyapi.t_result_u_u_get, _ollyapi.t_result_u_u_set)
    l = _swig_property(_ollyapi.t_result_u_l_get, _ollyapi.t_result_u_l_set)
    f = _swig_property(_ollyapi.t_result_u_f_get, _ollyapi.t_result_u_f_set)
    def __init__(self): 
        this = _ollyapi.new_t_result_u()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ollyapi.delete_t_result_u
    __del__ = lambda self : None;
t_result_u_swigregister = _ollyapi.t_result_u_swigregister
t_result_u_swigregister(t_result_u)

class t_thread(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    threadid = _swig_property(_ollyapi.t_thread_threadid_get, _ollyapi.t_thread_threadid_set)
    dummy = _swig_property(_ollyapi.t_thread_dummy_get, _ollyapi.t_thread_dummy_set)
    type = _swig_property(_ollyapi.t_thread_type_get, _ollyapi.t_thread_type_set)
    thread = _swig_property(_ollyapi.t_thread_thread_get, _ollyapi.t_thread_thread_set)
    datablock = _swig_property(_ollyapi.t_thread_datablock_get, _ollyapi.t_thread_datablock_set)
    entry = _swig_property(_ollyapi.t_thread_entry_get, _ollyapi.t_thread_entry_set)
    stacktop = _swig_property(_ollyapi.t_thread_stacktop_get, _ollyapi.t_thread_stacktop_set)
    stackbottom = _swig_property(_ollyapi.t_thread_stackbottom_get, _ollyapi.t_thread_stackbottom_set)
    context = _swig_property(_ollyapi.t_thread_context_get, _ollyapi.t_thread_context_set)
    reg = _swig_property(_ollyapi.t_thread_reg_get, _ollyapi.t_thread_reg_set)
    regvalid = _swig_property(_ollyapi.t_thread_regvalid_get, _ollyapi.t_thread_regvalid_set)
    oldreg = _swig_property(_ollyapi.t_thread_oldreg_get, _ollyapi.t_thread_oldreg_set)
    oldregvalid = _swig_property(_ollyapi.t_thread_oldregvalid_get, _ollyapi.t_thread_oldregvalid_set)
    suspendcount = _swig_property(_ollyapi.t_thread_suspendcount_get, _ollyapi.t_thread_suspendcount_set)
    usertime = _swig_property(_ollyapi.t_thread_usertime_get, _ollyapi.t_thread_usertime_set)
    systime = _swig_property(_ollyapi.t_thread_systime_get, _ollyapi.t_thread_systime_set)
    reserved = _swig_property(_ollyapi.t_thread_reserved_get, _ollyapi.t_thread_reserved_set)
    def __init__(self): 
        this = _ollyapi.new_t_thread()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ollyapi.delete_t_thread
    __del__ = lambda self : None;
t_thread_swigregister = _ollyapi.t_thread_swigregister
t_thread_swigregister(t_thread)

MM_RESTORE = _ollyapi.MM_RESTORE
MM_SILENT = _ollyapi.MM_SILENT
MM_DELANAL = _ollyapi.MM_DELANAL
MM_RESILENT = _ollyapi.MM_RESILENT
class t_memory(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    base = _swig_property(_ollyapi.t_memory_base_get, _ollyapi.t_memory_base_set)
    size = _swig_property(_ollyapi.t_memory_size_get, _ollyapi.t_memory_size_set)
    type = _swig_property(_ollyapi.t_memory_type_get, _ollyapi.t_memory_type_set)
    owner = _swig_property(_ollyapi.t_memory_owner_get, _ollyapi.t_memory_owner_set)
    initaccess = _swig_property(_ollyapi.t_memory_initaccess_get, _ollyapi.t_memory_initaccess_set)
    access = _swig_property(_ollyapi.t_memory_access_get, _ollyapi.t_memory_access_set)
    threadid = _swig_property(_ollyapi.t_memory_threadid_get, _ollyapi.t_memory_threadid_set)
    sect = _swig_property(_ollyapi.t_memory_sect_get, _ollyapi.t_memory_sect_set)
    copy = _swig_property(_ollyapi.t_memory_copy_get, _ollyapi.t_memory_copy_set)
    reserved = _swig_property(_ollyapi.t_memory_reserved_get, _ollyapi.t_memory_reserved_set)
    def __init__(self): 
        this = _ollyapi.new_t_memory()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ollyapi.delete_t_memory
    __del__ = lambda self : None;
t_memory_swigregister = _ollyapi.t_memory_swigregister
t_memory_swigregister(t_memory)

class t_heap(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    base = _swig_property(_ollyapi.t_heap_base_get, _ollyapi.t_heap_base_set)
    size = _swig_property(_ollyapi.t_heap_size_get, _ollyapi.t_heap_size_set)
    type = _swig_property(_ollyapi.t_heap_type_get, _ollyapi.t_heap_type_set)
    parent = _swig_property(_ollyapi.t_heap_parent_get, _ollyapi.t_heap_parent_set)
    def __init__(self): 
        this = _ollyapi.new_t_heap()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ollyapi.delete_t_heap
    __del__ = lambda self : None;
t_heap_swigregister = _ollyapi.t_heap_swigregister
t_heap_swigregister(t_heap)

NVERS = _ollyapi.NVERS
JT_JUMP = _ollyapi.JT_JUMP
JT_COND = _ollyapi.JT_COND
JT_SWITCH = _ollyapi.JT_SWITCH
class t_ahint(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    addr = _swig_property(_ollyapi.t_ahint_addr_get, _ollyapi.t_ahint_addr_set)
    size = _swig_property(_ollyapi.t_ahint_size_get, _ollyapi.t_ahint_size_set)
    type = _swig_property(_ollyapi.t_ahint_type_get, _ollyapi.t_ahint_type_set)
    def __init__(self): 
        this = _ollyapi.new_t_ahint()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ollyapi.delete_t_ahint
    __del__ = lambda self : None;
t_ahint_swigregister = _ollyapi.t_ahint_swigregister
t_ahint_swigregister(t_ahint)

class t_stringtable(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    name = _swig_property(_ollyapi.t_stringtable_name_get, _ollyapi.t_stringtable_name_set)
    language = _swig_property(_ollyapi.t_stringtable_language_get, _ollyapi.t_stringtable_language_set)
    addr = _swig_property(_ollyapi.t_stringtable_addr_get, _ollyapi.t_stringtable_addr_set)
    size = _swig_property(_ollyapi.t_stringtable_size_get, _ollyapi.t_stringtable_size_set)
    def __init__(self): 
        this = _ollyapi.new_t_stringtable()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ollyapi.delete_t_stringtable
    __del__ = lambda self : None;
t_stringtable_swigregister = _ollyapi.t_stringtable_swigregister
t_stringtable_swigregister(t_stringtable)

class t_fixup(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    base = _swig_property(_ollyapi.t_fixup_base_get, _ollyapi.t_fixup_base_set)
    size = _swig_property(_ollyapi.t_fixup_size_get, _ollyapi.t_fixup_size_set)
    def __init__(self): 
        this = _ollyapi.new_t_fixup()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ollyapi.delete_t_fixup
    __del__ = lambda self : None;
t_fixup_swigregister = _ollyapi.t_fixup_swigregister
t_fixup_swigregister(t_fixup)

class t_symvar(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    next = _swig_property(_ollyapi.t_symvar_next_get, _ollyapi.t_symvar_next_set)
    kind = _swig_property(_ollyapi.t_symvar_kind_get, _ollyapi.t_symvar_kind_set)
    type = _swig_property(_ollyapi.t_symvar_type_get, _ollyapi.t_symvar_type_set)
    regs = _swig_property(_ollyapi.t_symvar_regs_get, _ollyapi.t_symvar_regs_set)
    addr = _swig_property(_ollyapi.t_symvar_addr_get, _ollyapi.t_symvar_addr_set)
    offset = _swig_property(_ollyapi.t_symvar_offset_get, _ollyapi.t_symvar_offset_set)
    size = _swig_property(_ollyapi.t_symvar_size_get, _ollyapi.t_symvar_size_set)
    optvar = _swig_property(_ollyapi.t_symvar_optvar_get, _ollyapi.t_symvar_optvar_set)
    nameaddr = _swig_property(_ollyapi.t_symvar_nameaddr_get, _ollyapi.t_symvar_nameaddr_set)
    def __init__(self): 
        this = _ollyapi.new_t_symvar()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ollyapi.delete_t_symvar
    __del__ = lambda self : None;
t_symvar_swigregister = _ollyapi.t_symvar_swigregister
t_symvar_swigregister(t_symvar)

class t_jdest(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    type = _swig_property(_ollyapi.t_jdest_type_get, _ollyapi.t_jdest_type_set)
    from_ = _swig_property(_ollyapi.t_jdest_from__get, _ollyapi.t_jdest_from__set)
    to = _swig_property(_ollyapi.t_jdest_to_get, _ollyapi.t_jdest_to_set)
    def __init__(self): 
        this = _ollyapi.new_t_jdest()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ollyapi.delete_t_jdest
    __del__ = lambda self : None;
t_jdest_swigregister = _ollyapi.t_jdest_swigregister
t_jdest_swigregister(t_jdest)

class t_module(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    base = _swig_property(_ollyapi.t_module_base_get, _ollyapi.t_module_base_set)
    size = _swig_property(_ollyapi.t_module_size_get, _ollyapi.t_module_size_set)
    type = _swig_property(_ollyapi.t_module_type_get, _ollyapi.t_module_type_set)
    codebase = _swig_property(_ollyapi.t_module_codebase_get, _ollyapi.t_module_codebase_set)
    codesize = _swig_property(_ollyapi.t_module_codesize_get, _ollyapi.t_module_codesize_set)
    resbase = _swig_property(_ollyapi.t_module_resbase_get, _ollyapi.t_module_resbase_set)
    ressize = _swig_property(_ollyapi.t_module_ressize_get, _ollyapi.t_module_ressize_set)
    stringtable = _swig_property(_ollyapi.t_module_stringtable_get, _ollyapi.t_module_stringtable_set)
    nstringtable = _swig_property(_ollyapi.t_module_nstringtable_get, _ollyapi.t_module_nstringtable_set)
    maxstringtable = _swig_property(_ollyapi.t_module_maxstringtable_get, _ollyapi.t_module_maxstringtable_set)
    entry = _swig_property(_ollyapi.t_module_entry_get, _ollyapi.t_module_entry_set)
    database = _swig_property(_ollyapi.t_module_database_get, _ollyapi.t_module_database_set)
    idatatable = _swig_property(_ollyapi.t_module_idatatable_get, _ollyapi.t_module_idatatable_set)
    idatabase = _swig_property(_ollyapi.t_module_idatabase_get, _ollyapi.t_module_idatabase_set)
    edatatable = _swig_property(_ollyapi.t_module_edatatable_get, _ollyapi.t_module_edatatable_set)
    edatasize = _swig_property(_ollyapi.t_module_edatasize_get, _ollyapi.t_module_edatasize_set)
    reloctable = _swig_property(_ollyapi.t_module_reloctable_get, _ollyapi.t_module_reloctable_set)
    relocsize = _swig_property(_ollyapi.t_module_relocsize_get, _ollyapi.t_module_relocsize_set)
    name = _swig_property(_ollyapi.t_module_name_get, _ollyapi.t_module_name_set)
    path = _swig_property(_ollyapi.t_module_path_get, _ollyapi.t_module_path_set)
    nsect = _swig_property(_ollyapi.t_module_nsect_get, _ollyapi.t_module_nsect_set)
    sect = _swig_property(_ollyapi.t_module_sect_get, _ollyapi.t_module_sect_set)
    headersize = _swig_property(_ollyapi.t_module_headersize_get, _ollyapi.t_module_headersize_set)
    fixupbase = _swig_property(_ollyapi.t_module_fixupbase_get, _ollyapi.t_module_fixupbase_set)
    nfixup = _swig_property(_ollyapi.t_module_nfixup_get, _ollyapi.t_module_nfixup_set)
    fixup = _swig_property(_ollyapi.t_module_fixup_get, _ollyapi.t_module_fixup_set)
    codedec = _swig_property(_ollyapi.t_module_codedec_get, _ollyapi.t_module_codedec_set)
    codecrc = _swig_property(_ollyapi.t_module_codecrc_get, _ollyapi.t_module_codecrc_set)
    hittrace = _swig_property(_ollyapi.t_module_hittrace_get, _ollyapi.t_module_hittrace_set)
    hittracecopy = _swig_property(_ollyapi.t_module_hittracecopy_get, _ollyapi.t_module_hittracecopy_set)
    datadec = _swig_property(_ollyapi.t_module_datadec_get, _ollyapi.t_module_datadec_set)
    namelist = _swig_property(_ollyapi.t_module_namelist_get, _ollyapi.t_module_namelist_set)
    symvar = _swig_property(_ollyapi.t_module_symvar_get, _ollyapi.t_module_symvar_set)
    nsymvar = _swig_property(_ollyapi.t_module_nsymvar_get, _ollyapi.t_module_nsymvar_set)
    maxsymvar = _swig_property(_ollyapi.t_module_maxsymvar_get, _ollyapi.t_module_maxsymvar_set)
    globaltypes = _swig_property(_ollyapi.t_module_globaltypes_get, _ollyapi.t_module_globaltypes_set)
    mainentry = _swig_property(_ollyapi.t_module_mainentry_get, _ollyapi.t_module_mainentry_set)
    realsfxentry = _swig_property(_ollyapi.t_module_realsfxentry_get, _ollyapi.t_module_realsfxentry_set)
    updatenamelist = _swig_property(_ollyapi.t_module_updatenamelist_get, _ollyapi.t_module_updatenamelist_set)
    origcodesize = _swig_property(_ollyapi.t_module_origcodesize_get, _ollyapi.t_module_origcodesize_set)
    sfxbase = _swig_property(_ollyapi.t_module_sfxbase_get, _ollyapi.t_module_sfxbase_set)
    sfxsize = _swig_property(_ollyapi.t_module_sfxsize_get, _ollyapi.t_module_sfxsize_set)
    issystemdll = _swig_property(_ollyapi.t_module_issystemdll_get, _ollyapi.t_module_issystemdll_set)
    processed = _swig_property(_ollyapi.t_module_processed_get, _ollyapi.t_module_processed_set)
    dbghelpsym = _swig_property(_ollyapi.t_module_dbghelpsym_get, _ollyapi.t_module_dbghelpsym_set)
    version = _swig_property(_ollyapi.t_module_version_get, _ollyapi.t_module_version_set)
    jddata = _swig_property(_ollyapi.t_module_jddata_get, _ollyapi.t_module_jddata_set)
    njddata = _swig_property(_ollyapi.t_module_njddata_get, _ollyapi.t_module_njddata_set)
    reserved = _swig_property(_ollyapi.t_module_reserved_get, _ollyapi.t_module_reserved_set)
    def __init__(self): 
        this = _ollyapi.new_t_module()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ollyapi.delete_t_module
    __del__ = lambda self : None;
t_module_swigregister = _ollyapi.t_module_swigregister
t_module_swigregister(t_module)

DU_ESCAPABLE = _ollyapi.DU_ESCAPABLE
DU_BACKUP = _ollyapi.DU_BACKUP
DU_TYPE = _ollyapi.DU_TYPE
DU_COUNT = _ollyapi.DU_COUNT
DU_SIZE = _ollyapi.DU_SIZE
DU_UNDEF = _ollyapi.DU_UNDEF
DU_HEXTEXT = _ollyapi.DU_HEXTEXT
DU_TEXT = _ollyapi.DU_TEXT
DU_UNICODE = _ollyapi.DU_UNICODE
DU_INT = _ollyapi.DU_INT
DU_UINT = _ollyapi.DU_UINT
DU_IHEX = _ollyapi.DU_IHEX
DU_FLOAT = _ollyapi.DU_FLOAT
DU_ADDR = _ollyapi.DU_ADDR
DU_DISASM = _ollyapi.DU_DISASM
DU_HEXUNI = _ollyapi.DU_HEXUNI
DU_ADRASC = _ollyapi.DU_ADRASC
DU_ADRUNI = _ollyapi.DU_ADRUNI
DU_SPEC = _ollyapi.DU_SPEC
MT_BACKUP = _ollyapi.MT_BACKUP
MT_COPY = _ollyapi.MT_COPY
MT_EDIT = _ollyapi.MT_EDIT
MT_SEARCH = _ollyapi.MT_SEARCH
MT_DHISTORY = _ollyapi.MT_DHISTORY
class t_dump(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    table = _swig_property(_ollyapi.t_dump_table_get, _ollyapi.t_dump_table_set)
    dimmed = _swig_property(_ollyapi.t_dump_dimmed_get, _ollyapi.t_dump_dimmed_set)
    threadid = _swig_property(_ollyapi.t_dump_threadid_get, _ollyapi.t_dump_threadid_set)
    dumptype = _swig_property(_ollyapi.t_dump_dumptype_get, _ollyapi.t_dump_dumptype_set)
    specdump = _swig_property(_ollyapi.t_dump_specdump_get, _ollyapi.t_dump_specdump_set)
    menutype = _swig_property(_ollyapi.t_dump_menutype_get, _ollyapi.t_dump_menutype_set)
    itemwidth = _swig_property(_ollyapi.t_dump_itemwidth_get, _ollyapi.t_dump_itemwidth_set)
    showstackframes = _swig_property(_ollyapi.t_dump_showstackframes_get, _ollyapi.t_dump_showstackframes_set)
    showstacklocals = _swig_property(_ollyapi.t_dump_showstacklocals_get, _ollyapi.t_dump_showstacklocals_set)
    commentmode = _swig_property(_ollyapi.t_dump_commentmode_get, _ollyapi.t_dump_commentmode_set)
    filename = _swig_property(_ollyapi.t_dump_filename_get, _ollyapi.t_dump_filename_set)
    base = _swig_property(_ollyapi.t_dump_base_get, _ollyapi.t_dump_base_set)
    size = _swig_property(_ollyapi.t_dump_size_get, _ollyapi.t_dump_size_set)
    addr = _swig_property(_ollyapi.t_dump_addr_get, _ollyapi.t_dump_addr_set)
    lastaddr = _swig_property(_ollyapi.t_dump_lastaddr_get, _ollyapi.t_dump_lastaddr_set)
    sel0 = _swig_property(_ollyapi.t_dump_sel0_get, _ollyapi.t_dump_sel0_set)
    sel1 = _swig_property(_ollyapi.t_dump_sel1_get, _ollyapi.t_dump_sel1_set)
    startsel = _swig_property(_ollyapi.t_dump_startsel_get, _ollyapi.t_dump_startsel_set)
    captured = _swig_property(_ollyapi.t_dump_captured_get, _ollyapi.t_dump_captured_set)
    reladdr = _swig_property(_ollyapi.t_dump_reladdr_get, _ollyapi.t_dump_reladdr_set)
    relname = _swig_property(_ollyapi.t_dump_relname_get, _ollyapi.t_dump_relname_set)
    filecopy = _swig_property(_ollyapi.t_dump_filecopy_get, _ollyapi.t_dump_filecopy_set)
    backup = _swig_property(_ollyapi.t_dump_backup_get, _ollyapi.t_dump_backup_set)
    runtraceoffset = _swig_property(_ollyapi.t_dump_runtraceoffset_get, _ollyapi.t_dump_runtraceoffset_set)
    reserved = _swig_property(_ollyapi.t_dump_reserved_get, _ollyapi.t_dump_reserved_set)
    def __init__(self): 
        this = _ollyapi.new_t_dump()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ollyapi.delete_t_dump
    __del__ = lambda self : None;
t_dump_swigregister = _ollyapi.t_dump_swigregister
t_dump_swigregister(t_dump)

MAXTRACK = _ollyapi.MAXTRACK
MOVETOP = _ollyapi.MOVETOP
MOVEBOTTOM = _ollyapi.MOVEBOTTOM
CONT_BROADCAST = _ollyapi.CONT_BROADCAST
STOP_BROADCAST = _ollyapi.STOP_BROADCAST
BKUP_CREATE = _ollyapi.BKUP_CREATE
BKUP_VIEWDATA = _ollyapi.BKUP_VIEWDATA
BKUP_VIEWCOPY = _ollyapi.BKUP_VIEWCOPY
BKUP_LOADCOPY = _ollyapi.BKUP_LOADCOPY
BKUP_SAVEDATA = _ollyapi.BKUP_SAVEDATA
BKUP_SAVECOPY = _ollyapi.BKUP_SAVECOPY
BKUP_DELETE = _ollyapi.BKUP_DELETE
class t_ref(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    addr = _swig_property(_ollyapi.t_ref_addr_get, _ollyapi.t_ref_addr_set)
    size = _swig_property(_ollyapi.t_ref_size_get, _ollyapi.t_ref_size_set)
    type = _swig_property(_ollyapi.t_ref_type_get, _ollyapi.t_ref_type_set)
    dest = _swig_property(_ollyapi.t_ref_dest_get, _ollyapi.t_ref_dest_set)
    def __init__(self): 
        this = _ollyapi.new_t_ref()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ollyapi.delete_t_ref
    __del__ = lambda self : None;
t_ref_swigregister = _ollyapi.t_ref_swigregister
t_ref_swigregister(t_ref)

MEMBP_READ = _ollyapi.MEMBP_READ
MEMBP_WRITE = _ollyapi.MEMBP_WRITE
MEMBP_SFX = _ollyapi.MEMBP_SFX
TR_HIT = _ollyapi.TR_HIT
TR_SET = _ollyapi.TR_SET
TR_RTSKIP = _ollyapi.TR_RTSKIP
TR_RTRACE = _ollyapi.TR_RTRACE
TR_TRACE = _ollyapi.TR_TRACE
HB_FREE = _ollyapi.HB_FREE
HB_CODE = _ollyapi.HB_CODE
HB_ACCESS = _ollyapi.HB_ACCESS
HB_WRITE = _ollyapi.HB_WRITE
HB_IO = _ollyapi.HB_IO
HB_ONESHOT = _ollyapi.HB_ONESHOT
HB_STOPAN = _ollyapi.HB_STOPAN
HB_TEMP = _ollyapi.HB_TEMP
ATR_ADD = _ollyapi.ATR_ADD
ATR_ADDPROC = _ollyapi.ATR_ADDPROC
ATR_RESET = _ollyapi.ATR_RESET
ATR_REMOVE = _ollyapi.ATR_REMOVE
ATR_REMOVEALL = _ollyapi.ATR_REMOVEALL
ATR_RESTORE = _ollyapi.ATR_RESTORE
ATR_RTRADD = _ollyapi.ATR_RTRADD
ATR_RTRJUMPS = _ollyapi.ATR_RTRJUMPS
ATR_RTRENTRY = _ollyapi.ATR_RTRENTRY
ATR_RTREMOVE = _ollyapi.ATR_RTREMOVE
ATR_RTSKIP = _ollyapi.ATR_RTSKIP
COND_NOBREAK = _ollyapi.COND_NOBREAK
COND_LOGTRUE = _ollyapi.COND_LOGTRUE
COND_LOGALWAYS = _ollyapi.COND_LOGALWAYS
COND_ARGTRUE = _ollyapi.COND_ARGTRUE
COND_ARGALWAYS = _ollyapi.COND_ARGALWAYS
COND_BRKALWAYS = _ollyapi.COND_BRKALWAYS
COND_MASK = _ollyapi.COND_MASK
COND_FILLING = _ollyapi.COND_FILLING
class t_bpoint(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    addr = _swig_property(_ollyapi.t_bpoint_addr_get, _ollyapi.t_bpoint_addr_set)
    dummy = _swig_property(_ollyapi.t_bpoint_dummy_get, _ollyapi.t_bpoint_dummy_set)
    type = _swig_property(_ollyapi.t_bpoint_type_get, _ollyapi.t_bpoint_type_set)
    cmd = _swig_property(_ollyapi.t_bpoint_cmd_get, _ollyapi.t_bpoint_cmd_set)
    passcount = _swig_property(_ollyapi.t_bpoint_passcount_get, _ollyapi.t_bpoint_passcount_set)
    def __init__(self): 
        this = _ollyapi.new_t_bpoint()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ollyapi.delete_t_bpoint
    __del__ = lambda self : None;
t_bpoint_swigregister = _ollyapi.t_bpoint_swigregister
t_bpoint_swigregister(t_bpoint)

class t_hardbpoint(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    addr = _swig_property(_ollyapi.t_hardbpoint_addr_get, _ollyapi.t_hardbpoint_addr_set)
    size = _swig_property(_ollyapi.t_hardbpoint_size_get, _ollyapi.t_hardbpoint_size_set)
    type = _swig_property(_ollyapi.t_hardbpoint_type_get, _ollyapi.t_hardbpoint_type_set)
    reserved = _swig_property(_ollyapi.t_hardbpoint_reserved_get, _ollyapi.t_hardbpoint_reserved_set)
    def __init__(self): 
        this = _ollyapi.new_t_hardbpoint()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ollyapi.delete_t_hardbpoint
    __del__ = lambda self : None;
t_hardbpoint_swigregister = _ollyapi.t_hardbpoint_swigregister
t_hardbpoint_swigregister(t_hardbpoint)

class t_inject(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    codesize = _swig_property(_ollyapi.t_inject_codesize_get, _ollyapi.t_inject_codesize_set)
    code = _swig_property(_ollyapi.t_inject_code_get, _ollyapi.t_inject_code_set)
    stacksize = _swig_property(_ollyapi.t_inject_stacksize_get, _ollyapi.t_inject_stacksize_set)
    datatype = _swig_property(_ollyapi.t_inject_datatype_get, _ollyapi.t_inject_datatype_set)
    def __init__(self): 
        this = _ollyapi.new_t_inject()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ollyapi.delete_t_inject
    __del__ = lambda self : None;
t_inject_swigregister = _ollyapi.t_inject_swigregister
t_inject_swigregister(t_inject)

CPU_ASMHIST = _ollyapi.CPU_ASMHIST
CPU_ASMCENTER = _ollyapi.CPU_ASMCENTER
CPU_ASMFOCUS = _ollyapi.CPU_ASMFOCUS
CPU_DUMPHIST = _ollyapi.CPU_DUMPHIST
CPU_DUMPFIRST = _ollyapi.CPU_DUMPFIRST
CPU_DUMPFOCUS = _ollyapi.CPU_DUMPFOCUS
CPU_REGAUTO = _ollyapi.CPU_REGAUTO
CPU_RUNTRACE = _ollyapi.CPU_RUNTRACE
CPU_STACKFOCUS = _ollyapi.CPU_STACKFOCUS
CPU_NOCREATE = _ollyapi.CPU_NOCREATE
CPU_REDRAW = _ollyapi.CPU_REDRAW
CPU_NOFOCUS = _ollyapi.CPU_NOFOCUS
STEP_SAME = _ollyapi.STEP_SAME
STEP_RUN = _ollyapi.STEP_RUN
STEP_OVER = _ollyapi.STEP_OVER
STEP_IN = _ollyapi.STEP_IN
STEP_SKIP = _ollyapi.STEP_SKIP
STAT_NONE = _ollyapi.STAT_NONE
STAT_STOPPED = _ollyapi.STAT_STOPPED
STAT_EVENT = _ollyapi.STAT_EVENT
STAT_RUNNING = _ollyapi.STAT_RUNNING
STAT_FINISHED = _ollyapi.STAT_FINISHED
STAT_CLOSING = _ollyapi.STAT_CLOSING
DASC_TEST = _ollyapi.DASC_TEST
DASC_NOHEX = _ollyapi.DASC_NOHEX
DASC_ASCII = _ollyapi.DASC_ASCII
DASC_PASCAL = _ollyapi.DASC_PASCAL
FIRST_CODE_LINE = _ollyapi.FIRST_CODE_LINE
class t_sourceline(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    addr = _swig_property(_ollyapi.t_sourceline_addr_get, _ollyapi.t_sourceline_addr_set)
    size = _swig_property(_ollyapi.t_sourceline_size_get, _ollyapi.t_sourceline_size_set)
    srcname = _swig_property(_ollyapi.t_sourceline_srcname_get, _ollyapi.t_sourceline_srcname_set)
    line = _swig_property(_ollyapi.t_sourceline_line_get, _ollyapi.t_sourceline_line_set)
    def __init__(self): 
        this = _ollyapi.new_t_sourceline()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ollyapi.delete_t_sourceline
    __del__ = lambda self : None;
t_sourceline_swigregister = _ollyapi.t_sourceline_swigregister
t_sourceline_swigregister(t_sourceline)

MAXNEST = _ollyapi.MAXNEST
class t_window(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    hwnd = _swig_property(_ollyapi.t_window_hwnd_get, _ollyapi.t_window_hwnd_set)
    dummy = _swig_property(_ollyapi.t_window_dummy_get, _ollyapi.t_window_dummy_set)
    type = _swig_property(_ollyapi.t_window_type_get, _ollyapi.t_window_type_set)
    parenthw = _swig_property(_ollyapi.t_window_parenthw_get, _ollyapi.t_window_parenthw_set)
    winproc = _swig_property(_ollyapi.t_window_winproc_get, _ollyapi.t_window_winproc_set)
    threadid = _swig_property(_ollyapi.t_window_threadid_get, _ollyapi.t_window_threadid_set)
    exstyle = _swig_property(_ollyapi.t_window_exstyle_get, _ollyapi.t_window_exstyle_set)
    style = _swig_property(_ollyapi.t_window_style_get, _ollyapi.t_window_style_set)
    id = _swig_property(_ollyapi.t_window_id_get, _ollyapi.t_window_id_set)
    classproc = _swig_property(_ollyapi.t_window_classproc_get, _ollyapi.t_window_classproc_set)
    child = _swig_property(_ollyapi.t_window_child_get, _ollyapi.t_window_child_set)
    level = _swig_property(_ollyapi.t_window_level_get, _ollyapi.t_window_level_set)
    sibling = _swig_property(_ollyapi.t_window_sibling_get, _ollyapi.t_window_sibling_set)
    byparent = _swig_property(_ollyapi.t_window_byparent_get, _ollyapi.t_window_byparent_set)
    title = _swig_property(_ollyapi.t_window_title_get, _ollyapi.t_window_title_set)
    classname = _swig_property(_ollyapi.t_window_classname_get, _ollyapi.t_window_classname_set)
    tree = _swig_property(_ollyapi.t_window_tree_get, _ollyapi.t_window_tree_set)
    def __init__(self): 
        this = _ollyapi.new_t_window()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ollyapi.delete_t_window
    __del__ = lambda self : None;
t_window_swigregister = _ollyapi.t_window_swigregister
t_window_swigregister(t_window)

class t_patch(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    addr = _swig_property(_ollyapi.t_patch_addr_get, _ollyapi.t_patch_addr_set)
    size = _swig_property(_ollyapi.t_patch_size_get, _ollyapi.t_patch_size_set)
    type = _swig_property(_ollyapi.t_patch_type_get, _ollyapi.t_patch_type_set)
    orig = _swig_property(_ollyapi.t_patch_orig_get, _ollyapi.t_patch_orig_set)
    mod = _swig_property(_ollyapi.t_patch_mod_get, _ollyapi.t_patch_mod_set)
    def __init__(self): 
        this = _ollyapi.new_t_patch()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ollyapi.delete_t_patch
    __del__ = lambda self : None;
t_patch_swigregister = _ollyapi.t_patch_swigregister
t_patch_swigregister(t_patch)

VAL_HINST = _ollyapi.VAL_HINST
VAL_HWMAIN = _ollyapi.VAL_HWMAIN
VAL_HWCLIENT = _ollyapi.VAL_HWCLIENT
VAL_NCOLORS = _ollyapi.VAL_NCOLORS
VAL_COLORS = _ollyapi.VAL_COLORS
VAL_BRUSHES = _ollyapi.VAL_BRUSHES
VAL_PENS = _ollyapi.VAL_PENS
VAL_NFONTS = _ollyapi.VAL_NFONTS
VAL_FONTS = _ollyapi.VAL_FONTS
VAL_FONTNAMES = _ollyapi.VAL_FONTNAMES
VAL_FONTWIDTHS = _ollyapi.VAL_FONTWIDTHS
VAL_FONTHEIGHTS = _ollyapi.VAL_FONTHEIGHTS
VAL_NFIXFONTS = _ollyapi.VAL_NFIXFONTS
VAL_DEFFONT = _ollyapi.VAL_DEFFONT
VAL_NSCHEMES = _ollyapi.VAL_NSCHEMES
VAL_SCHEMES = _ollyapi.VAL_SCHEMES
VAL_DEFSCHEME = _ollyapi.VAL_DEFSCHEME
VAL_DEFHSCROLL = _ollyapi.VAL_DEFHSCROLL
VAL_RESTOREWINDOWPOS = _ollyapi.VAL_RESTOREWINDOWPOS
VAL_HPROCESS = _ollyapi.VAL_HPROCESS
VAL_PROCESSID = _ollyapi.VAL_PROCESSID
VAL_HMAINTHREAD = _ollyapi.VAL_HMAINTHREAD
VAL_MAINTHREADID = _ollyapi.VAL_MAINTHREADID
VAL_MAINBASE = _ollyapi.VAL_MAINBASE
VAL_PROCESSNAME = _ollyapi.VAL_PROCESSNAME
VAL_EXEFILENAME = _ollyapi.VAL_EXEFILENAME
VAL_CURRENTDIR = _ollyapi.VAL_CURRENTDIR
VAL_SYSTEMDIR = _ollyapi.VAL_SYSTEMDIR
VAL_DECODEANYIP = _ollyapi.VAL_DECODEANYIP
VAL_PASCALSTRINGS = _ollyapi.VAL_PASCALSTRINGS
VAL_ONLYASCII = _ollyapi.VAL_ONLYASCII
VAL_DIACRITICALS = _ollyapi.VAL_DIACRITICALS
VAL_GLOBALSEARCH = _ollyapi.VAL_GLOBALSEARCH
VAL_ALIGNEDSEARCH = _ollyapi.VAL_ALIGNEDSEARCH
VAL_IGNORECASE = _ollyapi.VAL_IGNORECASE
VAL_SEARCHMARGIN = _ollyapi.VAL_SEARCHMARGIN
VAL_KEEPSELSIZE = _ollyapi.VAL_KEEPSELSIZE
VAL_MMXDISPLAY = _ollyapi.VAL_MMXDISPLAY
VAL_WINDOWFONT = _ollyapi.VAL_WINDOWFONT
VAL_TABSTOPS = _ollyapi.VAL_TABSTOPS
VAL_MODULES = _ollyapi.VAL_MODULES
VAL_MEMORY = _ollyapi.VAL_MEMORY
VAL_THREADS = _ollyapi.VAL_THREADS
VAL_BREAKPOINTS = _ollyapi.VAL_BREAKPOINTS
VAL_REFERENCES = _ollyapi.VAL_REFERENCES
VAL_SOURCELIST = _ollyapi.VAL_SOURCELIST
VAL_WATCHES = _ollyapi.VAL_WATCHES
VAL_CPUFEATURES = _ollyapi.VAL_CPUFEATURES
VAL_TRACEFILE = _ollyapi.VAL_TRACEFILE
VAL_ALIGNDIALOGS = _ollyapi.VAL_ALIGNDIALOGS
VAL_CPUDASM = _ollyapi.VAL_CPUDASM
VAL_CPUDDUMP = _ollyapi.VAL_CPUDDUMP
VAL_CPUDSTACK = _ollyapi.VAL_CPUDSTACK
VAL_APIHELP = _ollyapi.VAL_APIHELP
VAL_HARDBP = _ollyapi.VAL_HARDBP
VAL_PATCHES = _ollyapi.VAL_PATCHES
VAL_HINTS = _ollyapi.VAL_HINTS
PM_MAIN = _ollyapi.PM_MAIN
PM_DUMP = _ollyapi.PM_DUMP
PM_MODULES = _ollyapi.PM_MODULES
PM_MEMORY = _ollyapi.PM_MEMORY
PM_THREADS = _ollyapi.PM_THREADS
PM_BREAKPOINTS = _ollyapi.PM_BREAKPOINTS
PM_REFERENCES = _ollyapi.PM_REFERENCES
PM_RTRACE = _ollyapi.PM_RTRACE
PM_WATCHES = _ollyapi.PM_WATCHES
PM_WINDOWS = _ollyapi.PM_WINDOWS
PM_DISASM = _ollyapi.PM_DISASM
PM_CPUDUMP = _ollyapi.PM_CPUDUMP
PM_CPUSTACK = _ollyapi.PM_CPUSTACK
PM_CPUREGS = _ollyapi.PM_CPUREGS
PP_MAIN = _ollyapi.PP_MAIN
PP_EVENT = _ollyapi.PP_EVENT
PP_PAUSE = _ollyapi.PP_PAUSE
PP_TERMINATED = _ollyapi.PP_TERMINATED
PP_BYPROGRAM = _ollyapi.PP_BYPROGRAM
PP_INT3BREAK = _ollyapi.PP_INT3BREAK
PP_MEMBREAK = _ollyapi.PP_MEMBREAK
PP_HWBREAK = _ollyapi.PP_HWBREAK
PP_SINGLESTEP = _ollyapi.PP_SINGLESTEP
PP_EXCEPTION = _ollyapi.PP_EXCEPTION
PP_ACCESS = _ollyapi.PP_ACCESS
PP_GUARDED = _ollyapi.PP_GUARDED
MI_SIGNATURE = _ollyapi.MI_SIGNATURE
MI_VERSION = _ollyapi.MI_VERSION
MI_FILENAME = _ollyapi.MI_FILENAME
MI_FILESIZE = _ollyapi.MI_FILESIZE
MI_TIMESTAMP = _ollyapi.MI_TIMESTAMP
MI_SFXENTRY = _ollyapi.MI_SFXENTRY
MI_PATCH = _ollyapi.MI_PATCH
MI_USER = _ollyapi.MI_USER
MI_PROCDATA = _ollyapi.MI_PROCDATA
MI_SWDATA = _ollyapi.MI_SWDATA
MI_CALLFINT = _ollyapi.MI_CALLFINT
MI_CALLFMOD = _ollyapi.MI_CALLFMOD
MI_CALLFABS = _ollyapi.MI_CALLFABS
MI_INT3BREAK = _ollyapi.MI_INT3BREAK
MI_INT3BRKC = _ollyapi.MI_INT3BRKC
MI_HDWRBREAK = _ollyapi.MI_HDWRBREAK
MI_JDDATA = _ollyapi.MI_JDDATA
MI_ANALYSIS = _ollyapi.MI_ANALYSIS
MI_ANALPACK = _ollyapi.MI_ANALPACK
MI_AHINT = _ollyapi.MI_AHINT
MI_TRACE = _ollyapi.MI_TRACE
MI_TRACEPACK = _ollyapi.MI_TRACEPACK
MI_CODECRC = _ollyapi.MI_CODECRC
MI_SAVEAREA = _ollyapi.MI_SAVEAREA
MI_END = _ollyapi.MI_END
MI_WINJUG = _ollyapi.MI_WINJUG
MI_WINJU1 = _ollyapi.MI_WINJU1
MI_WINJU2 = _ollyapi.MI_WINJU2
MI_WINJU3 = _ollyapi.MI_WINJU3
MI_APPST = _ollyapi.MI_APPST

def Addtolist(*args):
  return _ollyapi.Addtolist(*args)
Addtolist = _ollyapi.Addtolist

def Updatelist():
  return _ollyapi.Updatelist()
Updatelist = _ollyapi.Updatelist

def Createlistwindow():
  return _ollyapi.Createlistwindow()
Createlistwindow = _ollyapi.Createlistwindow

def Error(*args):
  return _ollyapi.Error(*args)
Error = _ollyapi.Error

def Message(*args):
  return _ollyapi.Message(*args)
Message = _ollyapi.Message

def Infoline(*args):
  return _ollyapi.Infoline(*args)
Infoline = _ollyapi.Infoline

def Progress(*args):
  return _ollyapi.Progress(*args)
Progress = _ollyapi.Progress

def Flash(*args):
  return _ollyapi.Flash(*args)
Flash = _ollyapi.Flash

def Decodeaddress(*args):
  return _ollyapi.Decodeaddress(*args)
Decodeaddress = _ollyapi.Decodeaddress

def Decoderelativeoffset(*args):
  return _ollyapi.Decoderelativeoffset(*args)
Decoderelativeoffset = _ollyapi.Decoderelativeoffset

def Decodecharacter(*args):
  return _ollyapi.Decodecharacter(*args)
Decodecharacter = _ollyapi.Decodecharacter

def Printfloat4(*args):
  return _ollyapi.Printfloat4(*args)
Printfloat4 = _ollyapi.Printfloat4

def Printfloat8(*args):
  return _ollyapi.Printfloat8(*args)
Printfloat8 = _ollyapi.Printfloat8

def Printfloat10(*args):
  return _ollyapi.Printfloat10(*args)
Printfloat10 = _ollyapi.Printfloat10

def Print3dnow(*args):
  return _ollyapi.Print3dnow(*args)
Print3dnow = _ollyapi.Print3dnow

def Printsse(*args):
  return _ollyapi.Printsse(*args)
Printsse = _ollyapi.Printsse

def Followcall(*args):
  return _ollyapi.Followcall(*args)
Followcall = _ollyapi.Followcall

def Stringtotext(*args):
  return _ollyapi.Stringtotext(*args)
Stringtotext = _ollyapi.Stringtotext

def Getlong(*args):
  return _ollyapi.Getlong(*args)
Getlong = _ollyapi.Getlong

def Getlongxy(*args):
  return _ollyapi.Getlongxy(*args)
Getlongxy = _ollyapi.Getlongxy

def Getregxy(*args):
  return _ollyapi.Getregxy(*args)
Getregxy = _ollyapi.Getregxy

def Getline(*args):
  return _ollyapi.Getline(*args)
Getline = _ollyapi.Getline

def Getlinexy(*args):
  return _ollyapi.Getlinexy(*args)
Getlinexy = _ollyapi.Getlinexy

def Getfloat10(*args):
  return _ollyapi.Getfloat10(*args)
Getfloat10 = _ollyapi.Getfloat10

def Getfloat10xy(*args):
  return _ollyapi.Getfloat10xy(*args)
Getfloat10xy = _ollyapi.Getfloat10xy

def Getfloat(*args):
  return _ollyapi.Getfloat(*args)
Getfloat = _ollyapi.Getfloat

def Getfloatxy(*args):
  return _ollyapi.Getfloatxy(*args)
Getfloatxy = _ollyapi.Getfloatxy

def Getasmfindmodel(*args):
  return _ollyapi.Getasmfindmodel(*args)
Getasmfindmodel = _ollyapi.Getasmfindmodel

def Getasmfindmodelxy(*args):
  return _ollyapi.Getasmfindmodelxy(*args)
Getasmfindmodelxy = _ollyapi.Getasmfindmodelxy

def Gettext(*args):
  return _ollyapi.Gettext(*args)
Gettext = _ollyapi.Gettext

def Gettextxy(*args):
  return _ollyapi.Gettextxy(*args)
Gettextxy = _ollyapi.Gettextxy

def Gethexstring(*args):
  return _ollyapi.Gethexstring(*args)
Gethexstring = _ollyapi.Gethexstring

def Gethexstringxy(*args):
  return _ollyapi.Gethexstringxy(*args)
Gethexstringxy = _ollyapi.Gethexstringxy

def Getmmx(*args):
  return _ollyapi.Getmmx(*args)
Getmmx = _ollyapi.Getmmx

def Getmmxxy(*args):
  return _ollyapi.Getmmxxy(*args)
Getmmxxy = _ollyapi.Getmmxxy

def Get3dnow(*args):
  return _ollyapi.Get3dnow(*args)
Get3dnow = _ollyapi.Get3dnow

def Get3dnowxy(*args):
  return _ollyapi.Get3dnowxy(*args)
Get3dnowxy = _ollyapi.Get3dnowxy

def Browsefilename(*args):
  return _ollyapi.Browsefilename(*args)
Browsefilename = _ollyapi.Browsefilename

def OpenEXEfile(*args):
  return _ollyapi.OpenEXEfile(*args)
OpenEXEfile = _ollyapi.OpenEXEfile

def Attachtoactiveprocess(*args):
  return _ollyapi.Attachtoactiveprocess(*args)
Attachtoactiveprocess = _ollyapi.Attachtoactiveprocess

def Animate(*args):
  return _ollyapi.Animate(*args)
Animate = _ollyapi.Animate

def Createsorteddata(*args):
  return _ollyapi.Createsorteddata(*args)
Createsorteddata = _ollyapi.Createsorteddata

def Destroysorteddata(*args):
  return _ollyapi.Destroysorteddata(*args)
Destroysorteddata = _ollyapi.Destroysorteddata

def Addsorteddata(*args):
  return _ollyapi.Addsorteddata(*args)
Addsorteddata = _ollyapi.Addsorteddata

def Deletesorteddata(*args):
  return _ollyapi.Deletesorteddata(*args)
Deletesorteddata = _ollyapi.Deletesorteddata

def Deletesorteddatarange(*args):
  return _ollyapi.Deletesorteddatarange(*args)
Deletesorteddatarange = _ollyapi.Deletesorteddatarange

def Deletenonconfirmedsorteddata(*args):
  return _ollyapi.Deletenonconfirmedsorteddata(*args)
Deletenonconfirmedsorteddata = _ollyapi.Deletenonconfirmedsorteddata

def Findsorteddata(*args):
  return _ollyapi.Findsorteddata(*args)
Findsorteddata = _ollyapi.Findsorteddata

def Findsorteddatarange(*args):
  return _ollyapi.Findsorteddatarange(*args)
Findsorteddatarange = _ollyapi.Findsorteddatarange

def Findsorteddataindex(*args):
  return _ollyapi.Findsorteddataindex(*args)
Findsorteddataindex = _ollyapi.Findsorteddataindex

def Sortsorteddata(*args):
  return _ollyapi.Sortsorteddata(*args)
Sortsorteddata = _ollyapi.Sortsorteddata

def Getsortedbyselection(*args):
  return _ollyapi.Getsortedbyselection(*args)
Getsortedbyselection = _ollyapi.Getsortedbyselection

def Defaultbar(*args):
  return _ollyapi.Defaultbar(*args)
Defaultbar = _ollyapi.Defaultbar

def Tablefunction(*args):
  return _ollyapi.Tablefunction(*args)
Tablefunction = _ollyapi.Tablefunction

def Painttable(*args):
  return _ollyapi.Painttable(*args)
Painttable = _ollyapi.Painttable

def Gettableselectionxy(*args):
  return _ollyapi.Gettableselectionxy(*args)
Gettableselectionxy = _ollyapi.Gettableselectionxy

def Selectandscroll(*args):
  return _ollyapi.Selectandscroll(*args)
Selectandscroll = _ollyapi.Selectandscroll

def Insertname(*args):
  return _ollyapi.Insertname(*args)
Insertname = _ollyapi.Insertname

def Quickinsertname(*args):
  return _ollyapi.Quickinsertname(*args)
Quickinsertname = _ollyapi.Quickinsertname

def Mergequicknames():
  return _ollyapi.Mergequicknames()
Mergequicknames = _ollyapi.Mergequicknames

def Discardquicknames():
  return _ollyapi.Discardquicknames()
Discardquicknames = _ollyapi.Discardquicknames

def Findname(*args):
  return _ollyapi.Findname(*args)
Findname = _ollyapi.Findname

def Decodename(*args):
  return _ollyapi.Decodename(*args)
Decodename = _ollyapi.Decodename

def Findnextname(*args):
  return _ollyapi.Findnextname(*args)
Findnextname = _ollyapi.Findnextname

def Findlabel(*args):
  return _ollyapi.Findlabel(*args)
Findlabel = _ollyapi.Findlabel

def Deletenamerange(*args):
  return _ollyapi.Deletenamerange(*args)
Deletenamerange = _ollyapi.Deletenamerange

def Findlabelbyname(*args):
  return _ollyapi.Findlabelbyname(*args)
Findlabelbyname = _ollyapi.Findlabelbyname

def Findimportbyname(*args):
  return _ollyapi.Findimportbyname(*args)
Findimportbyname = _ollyapi.Findimportbyname

def Demanglename(*args):
  return _ollyapi.Demanglename(*args)
Demanglename = _ollyapi.Demanglename

def Findsymbolicname(*args):
  return _ollyapi.Findsymbolicname(*args)
Findsymbolicname = _ollyapi.Findsymbolicname

def Disasm(*args):
  return _ollyapi.Disasm(*args)
Disasm = _ollyapi.Disasm

def Disassembleback(*args):
  return _ollyapi.Disassembleback(*args)
Disassembleback = _ollyapi.Disassembleback

def Disassembleforward(*args):
  return _ollyapi.Disassembleforward(*args)
Disassembleforward = _ollyapi.Disassembleforward

def Issuspicious(*args):
  return _ollyapi.Issuspicious(*args)
Issuspicious = _ollyapi.Issuspicious

def Isfilling(*args):
  return _ollyapi.Isfilling(*args)
Isfilling = _ollyapi.Isfilling

def Assemble(*args):
  return _ollyapi.Assemble(*args)
Assemble = _ollyapi.Assemble

def Checkcondition(*args):
  return _ollyapi.Checkcondition(*args)
Checkcondition = _ollyapi.Checkcondition

def Expression(*args):
  return _ollyapi.Expression(*args)
Expression = _ollyapi.Expression

def Createthreadwindow():
  return _ollyapi.Createthreadwindow()
Createthreadwindow = _ollyapi.Createthreadwindow

def Findthread(*args):
  return _ollyapi.Findthread(*args)
Findthread = _ollyapi.Findthread

def Decodethreadname(*args):
  return _ollyapi.Decodethreadname(*args)
Decodethreadname = _ollyapi.Decodethreadname

def Getcputhreadid():
  return _ollyapi.Getcputhreadid()
Getcputhreadid = _ollyapi.Getcputhreadid

def Runsinglethread(*args):
  return _ollyapi.Runsinglethread(*args)
Runsinglethread = _ollyapi.Runsinglethread

def Restoreallthreads():
  return _ollyapi.Restoreallthreads()
Restoreallthreads = _ollyapi.Restoreallthreads

def Listmemory():
  return _ollyapi.Listmemory()
Listmemory = _ollyapi.Listmemory

def Findmemory(*args):
  return _ollyapi.Findmemory(*args)
Findmemory = _ollyapi.Findmemory

def Guardmemory(*args):
  return _ollyapi.Guardmemory(*args)
Guardmemory = _ollyapi.Guardmemory

def Havecopyofmemory(*args):
  return _ollyapi.Havecopyofmemory(*args)
Havecopyofmemory = _ollyapi.Havecopyofmemory

def Readmemory(*args):
  return _ollyapi.Readmemory(*args)
Readmemory = _ollyapi.Readmemory

def Writememory(*args):
  return _ollyapi.Writememory(*args)
Writememory = _ollyapi.Writememory

def Readcommand(*args):
  return _ollyapi.Readcommand(*args)
Readcommand = _ollyapi.Readcommand

def Findmodule(*args):
  return _ollyapi.Findmodule(*args)
Findmodule = _ollyapi.Findmodule

def Findfixup(*args):
  return _ollyapi.Findfixup(*args)
Findfixup = _ollyapi.Findfixup

def Finddecode(*args):
  return _ollyapi.Finddecode(*args)
Finddecode = _ollyapi.Finddecode

def Findfileoffset(*args):
  return _ollyapi.Findfileoffset(*args)
Findfileoffset = _ollyapi.Findfileoffset

def Decoderange(*args):
  return _ollyapi.Decoderange(*args)
Decoderange = _ollyapi.Decoderange

def Analysecode(*args):
  return _ollyapi.Analysecode(*args)
Analysecode = _ollyapi.Analysecode

def Registerotclass(*args):
  return _ollyapi.Registerotclass(*args)
Registerotclass = _ollyapi.Registerotclass

def Newtablewindow(*args):
  return _ollyapi.Newtablewindow(*args)
Newtablewindow = _ollyapi.Newtablewindow

def Quicktablewindow(*args):
  return _ollyapi.Quicktablewindow(*args)
Quicktablewindow = _ollyapi.Quicktablewindow

def Createdumpwindow(*args):
  return _ollyapi.Createdumpwindow(*args)
Createdumpwindow = _ollyapi.Createdumpwindow

def Setdumptype(*args):
  return _ollyapi.Setdumptype(*args)
Setdumptype = _ollyapi.Setdumptype

def Dumpbackup(*args):
  return _ollyapi.Dumpbackup(*args)
Dumpbackup = _ollyapi.Dumpbackup

def Broadcast(*args):
  return _ollyapi.Broadcast(*args)
Broadcast = _ollyapi.Broadcast

def Compress(*args):
  return _ollyapi.Compress(*args)
Compress = _ollyapi.Compress

def Getoriginaldatasize(*args):
  return _ollyapi.Getoriginaldatasize(*args)
Getoriginaldatasize = _ollyapi.Getoriginaldatasize

def Decompress(*args):
  return _ollyapi.Decompress(*args)
Decompress = _ollyapi.Decompress

def Calculatecrc(*args):
  return _ollyapi.Calculatecrc(*args)
Calculatecrc = _ollyapi.Calculatecrc

def Findreferences(*args):
  return _ollyapi.Findreferences(*args)
Findreferences = _ollyapi.Findreferences

def Findstrings(*args):
  return _ollyapi.Findstrings(*args)
Findstrings = _ollyapi.Findstrings

def Findalldllcalls(*args):
  return _ollyapi.Findalldllcalls(*args)
Findalldllcalls = _ollyapi.Findalldllcalls

def Findallcommands(*args):
  return _ollyapi.Findallcommands(*args)
Findallcommands = _ollyapi.Findallcommands

def Findallsequences(*args):
  return _ollyapi.Findallsequences(*args)
Findallsequences = _ollyapi.Findallsequences

def Walkreference(*args):
  return _ollyapi.Walkreference(*args)
Walkreference = _ollyapi.Walkreference

def Walkreferenceex(*args):
  return _ollyapi.Walkreferenceex(*args)
Walkreferenceex = _ollyapi.Walkreferenceex

def Setbreakpoint(*args):
  return _ollyapi.Setbreakpoint(*args)
Setbreakpoint = _ollyapi.Setbreakpoint

def Setbreakpointext(*args):
  return _ollyapi.Setbreakpointext(*args)
Setbreakpointext = _ollyapi.Setbreakpointext

def Manualbreakpoint(*args):
  return _ollyapi.Manualbreakpoint(*args)
Manualbreakpoint = _ollyapi.Manualbreakpoint

def Deletebreakpoints(*args):
  return _ollyapi.Deletebreakpoints(*args)
Deletebreakpoints = _ollyapi.Deletebreakpoints

def Getbreakpointtype(*args):
  return _ollyapi.Getbreakpointtype(*args)
Getbreakpointtype = _ollyapi.Getbreakpointtype

def Getbreakpointtypecount(*args):
  return _ollyapi.Getbreakpointtypecount(*args)
Getbreakpointtypecount = _ollyapi.Getbreakpointtypecount

def Getnextbreakpoint(*args):
  return _ollyapi.Getnextbreakpoint(*args)
Getnextbreakpoint = _ollyapi.Getnextbreakpoint

def Tempbreakpoint(*args):
  return _ollyapi.Tempbreakpoint(*args)
Tempbreakpoint = _ollyapi.Tempbreakpoint

def Hardbreakpoints(*args):
  return _ollyapi.Hardbreakpoints(*args)
Hardbreakpoints = _ollyapi.Hardbreakpoints

def Sethardwarebreakpoint(*args):
  return _ollyapi.Sethardwarebreakpoint(*args)
Sethardwarebreakpoint = _ollyapi.Sethardwarebreakpoint

def Deletehardwarebreakpoint(*args):
  return _ollyapi.Deletehardwarebreakpoint(*args)
Deletehardwarebreakpoint = _ollyapi.Deletehardwarebreakpoint

def Deletehardwarebreakbyaddr(*args):
  return _ollyapi.Deletehardwarebreakbyaddr(*args)
Deletehardwarebreakbyaddr = _ollyapi.Deletehardwarebreakbyaddr

def Setmembreakpoint(*args):
  return _ollyapi.Setmembreakpoint(*args)
Setmembreakpoint = _ollyapi.Setmembreakpoint

def Findhittrace(*args):
  return _ollyapi.Findhittrace(*args)
Findhittrace = _ollyapi.Findhittrace

def Modifyhittrace(*args):
  return _ollyapi.Modifyhittrace(*args)
Modifyhittrace = _ollyapi.Modifyhittrace

def Isretaddr(*args):
  return _ollyapi.Isretaddr(*args)
Isretaddr = _ollyapi.Isretaddr

def Creatertracewindow():
  return _ollyapi.Creatertracewindow()
Creatertracewindow = _ollyapi.Creatertracewindow

def Settracecondition(*args):
  return _ollyapi.Settracecondition(*args)
Settracecondition = _ollyapi.Settracecondition

def Settracecount(*args):
  return _ollyapi.Settracecount(*args)
Settracecount = _ollyapi.Settracecount

def Settracepauseoncommands(*args):
  return _ollyapi.Settracepauseoncommands(*args)
Settracepauseoncommands = _ollyapi.Settracepauseoncommands

def Startruntrace(*args):
  return _ollyapi.Startruntrace(*args)
Startruntrace = _ollyapi.Startruntrace

def Deleteruntrace():
  return _ollyapi.Deleteruntrace()
Deleteruntrace = _ollyapi.Deleteruntrace

def Runtracesize():
  return _ollyapi.Runtracesize()
Runtracesize = _ollyapi.Runtracesize

def Findprevruntraceip(*args):
  return _ollyapi.Findprevruntraceip(*args)
Findprevruntraceip = _ollyapi.Findprevruntraceip

def Findnextruntraceip(*args):
  return _ollyapi.Findnextruntraceip(*args)
Findnextruntraceip = _ollyapi.Findnextruntraceip

def Getruntraceregisters(*args):
  return _ollyapi.Getruntraceregisters(*args)
Getruntraceregisters = _ollyapi.Getruntraceregisters

def Getruntraceprofile(*args):
  return _ollyapi.Getruntraceprofile(*args)
Getruntraceprofile = _ollyapi.Getruntraceprofile

def Scrollruntracewindow(*args):
  return _ollyapi.Scrollruntracewindow(*args)
Scrollruntracewindow = _ollyapi.Scrollruntracewindow

def Createprofilewindow(*args):
  return _ollyapi.Createprofilewindow(*args)
Createprofilewindow = _ollyapi.Createprofilewindow

def Injectcode(*args):
  return _ollyapi.Injectcode(*args)
Injectcode = _ollyapi.Injectcode

def Setcpu(*args):
  return _ollyapi.Setcpu(*args)
Setcpu = _ollyapi.Setcpu

def Setdisasm(*args):
  return _ollyapi.Setdisasm(*args)
Setdisasm = _ollyapi.Setdisasm

def Redrawdisassembler():
  return _ollyapi.Redrawdisassembler()
Redrawdisassembler = _ollyapi.Redrawdisassembler

def Getdisassemblerrange(*args):
  return _ollyapi.Getdisassemblerrange(*args)
Getdisassemblerrange = _ollyapi.Getdisassemblerrange

def Findprocbegin(*args):
  return _ollyapi.Findprocbegin(*args)
Findprocbegin = _ollyapi.Findprocbegin

def Findprocend(*args):
  return _ollyapi.Findprocend(*args)
Findprocend = _ollyapi.Findprocend

def Findprevproc(*args):
  return _ollyapi.Findprevproc(*args)
Findprevproc = _ollyapi.Findprevproc

def Findnextproc(*args):
  return _ollyapi.Findnextproc(*args)
Findnextproc = _ollyapi.Findnextproc

def Getproclimits(*args):
  return _ollyapi.Getproclimits(*args)
Getproclimits = _ollyapi.Getproclimits

def Sendshortcut(*args):
  return _ollyapi.Sendshortcut(*args)
Sendshortcut = _ollyapi.Sendshortcut

def Getstatus():
  return _ollyapi.Getstatus()
Getstatus = _ollyapi.Getstatus

def Go(*args):
  return _ollyapi.Go(*args)
Go = _ollyapi.Go

def Suspendprocess(*args):
  return _ollyapi.Suspendprocess(*args)
Suspendprocess = _ollyapi.Suspendprocess

def Decodeknownargument(*args):
  return _ollyapi.Decodeknownargument(*args)
Decodeknownargument = _ollyapi.Decodeknownargument

def Findunknownfunction(*args):
  return _ollyapi.Findunknownfunction(*args)
Findunknownfunction = _ollyapi.Findunknownfunction

def Decodeascii(*args):
  return _ollyapi.Decodeascii(*args)
Decodeascii = _ollyapi.Decodeascii

def Decodeunicode(*args):
  return _ollyapi.Decodeunicode(*args)
Decodeunicode = _ollyapi.Decodeunicode

def Showsourcefromaddress(*args):
  return _ollyapi.Showsourcefromaddress(*args)
Showsourcefromaddress = _ollyapi.Showsourcefromaddress

def Getresourcestring(*args):
  return _ollyapi.Getresourcestring(*args)
Getresourcestring = _ollyapi.Getresourcestring

def Getlinefromaddress(*args):
  return _ollyapi.Getlinefromaddress(*args)
Getlinefromaddress = _ollyapi.Getlinefromaddress

def Getaddressfromline(*args):
  return _ollyapi.Getaddressfromline(*args)
Getaddressfromline = _ollyapi.Getaddressfromline

def Getsourcefilelimits(*args):
  return _ollyapi.Getsourcefilelimits(*args)
Getsourcefilelimits = _ollyapi.Getsourcefilelimits

def Decodefullvarname(*args):
  return _ollyapi.Decodefullvarname(*args)
Decodefullvarname = _ollyapi.Decodefullvarname

def Getbprelname(*args):
  return _ollyapi.Getbprelname(*args)
Getbprelname = _ollyapi.Getbprelname

def Createwatchwindow():
  return _ollyapi.Createwatchwindow()
Createwatchwindow = _ollyapi.Createwatchwindow

def Deletewatch(*args):
  return _ollyapi.Deletewatch(*args)
Deletewatch = _ollyapi.Deletewatch

def Insertwatch(*args):
  return _ollyapi.Insertwatch(*args)
Insertwatch = _ollyapi.Insertwatch

def Getwatch(*args):
  return _ollyapi.Getwatch(*args)
Getwatch = _ollyapi.Getwatch

def Createwinwindow():
  return _ollyapi.Createwinwindow()
Createwinwindow = _ollyapi.Createwinwindow

def Createpatchwindow():
  return _ollyapi.Createpatchwindow()
Createpatchwindow = _ollyapi.Createpatchwindow

def Registerpluginclass(*args):
  return _ollyapi.Registerpluginclass(*args)
Registerpluginclass = _ollyapi.Registerpluginclass

def Unregisterpluginclass(*args):
  return _ollyapi.Unregisterpluginclass(*args)
Unregisterpluginclass = _ollyapi.Unregisterpluginclass

def Pluginwriteinttoini(*args):
  return _ollyapi.Pluginwriteinttoini(*args)
Pluginwriteinttoini = _ollyapi.Pluginwriteinttoini

def Pluginwritestringtoini(*args):
  return _ollyapi.Pluginwritestringtoini(*args)
Pluginwritestringtoini = _ollyapi.Pluginwritestringtoini

def Pluginreadintfromini(*args):
  return _ollyapi.Pluginreadintfromini(*args)
Pluginreadintfromini = _ollyapi.Pluginreadintfromini

def Pluginreadstringfromini(*args):
  return _ollyapi.Pluginreadstringfromini(*args)
Pluginreadstringfromini = _ollyapi.Pluginreadstringfromini

def Pluginsaverecord(*args):
  return _ollyapi.Pluginsaverecord(*args)
Pluginsaverecord = _ollyapi.Pluginsaverecord

def Plugingetvalue(*args):
  return _ollyapi.Plugingetvalue(*args)
Plugingetvalue = _ollyapi.Plugingetvalue

def pluginvalue_to_t_table(*args):
  return _ollyapi.pluginvalue_to_t_table(*args)
pluginvalue_to_t_table = _ollyapi.pluginvalue_to_t_table

def pluginvalue_to_t_dump(*args):
  return _ollyapi.pluginvalue_to_t_dump(*args)
pluginvalue_to_t_dump = _ollyapi.pluginvalue_to_t_dump

def pluginvalue_to_t_sorted(*args):
  return _ollyapi.pluginvalue_to_t_sorted(*args)
pluginvalue_to_t_sorted = _ollyapi.pluginvalue_to_t_sorted

def void_to_t_memory(*args):
  return _ollyapi.void_to_t_memory(*args)
void_to_t_memory = _ollyapi.void_to_t_memory

def void_to_t_module(*args):
  return _ollyapi.void_to_t_module(*args)
void_to_t_module = _ollyapi.void_to_t_module

def void_to_t_thread(*args):
  return _ollyapi.void_to_t_thread(*args)
void_to_t_thread = _ollyapi.void_to_t_thread

def void_to_t_bpoint(*args):
  return _ollyapi.void_to_t_bpoint(*args)
void_to_t_bpoint = _ollyapi.void_to_t_bpoint

def void_to_t_ref(*args):
  return _ollyapi.void_to_t_ref(*args)
void_to_t_ref = _ollyapi.void_to_t_ref

def void_to_t_patch(*args):
  return _ollyapi.void_to_t_patch(*args)
void_to_t_patch = _ollyapi.void_to_t_patch


