<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros">
    <IDA_DIR>m:\!re\IDA92_x64\</IDA_DIR>
    <SDK_DIR>m:\!re\idasdk92\</SDK_DIR>
    <IDA_SUFFIX>92</IDA_SUFFIX>
    <QTDIR>m:\!re\depz\qt6.8.2_msvc2015_x64_qt_namespace\build6.8.2-x64\</QTDIR>
  </PropertyGroup>
  <PropertyGroup />
  <ItemDefinitionGroup />
  <ItemGroup>
    <BuildMacro Include="IDA_DIR">
      <Value>$(IDA_DIR)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="SDK_DIR">
      <Value>$(SDK_DIR)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="IDA_SUFFIX">
      <Value>$(IDA_SUFFIX)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="QTDIR">
      <Value>$(QTDIR)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
  </ItemGroup>
</Project>