name: Build Labeless

on:
  push:
    branches:
      - actions_ci
  pull_request:
    branches:
      - actions_ci

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # macos-14 - Apple Silicon ARM64, macOS Sonoma, ARM64 only.
        # macos-13: Supports both ARM64 and x86_64.
        # os: [ubuntu-20.04, windows-2022, macos-14]
        os: [ubuntu-20.04, windows-2019]
        include:
          #- os: ubuntu-20.04
          #  build_cmd: make
          - os: windows-2019
            build_cmd: build.bat
          #- os: macos-14
          #  build_cmd: ./build_macos.sh

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # - name: Restore VS Toolset Cache
    #   if: runner.os == 'Windows'
    #   uses: actions/cache@v3
    #   with:
    #     path: C:\Program Files (x86)\Microsoft Visual Studio
    #     key: vs-toolset-v140

    - name: Set outputs Non-Windows
      if: runner.os != 'Windows'
      run: |
        echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        VERSION_MAJOR=$(grep -E '\#define\s+VERSION_MAJOR\s+([0-9]+)' ./common/version.h | awk '{print $3}')
        VERSION_MINOR=$(grep -E '\#define\s+VERSION_MINOR\s+([0-9]+)' ./common/version.h | awk '{print $3}')
        VERSION_REVISION=$(grep -E '\#define\s+VERSION_REVISION\s+([0-9]+)' ./common/version.h | awk '{print $3}')
        VERSION_BUILD=$(grep -E '\#define\s+VERSION_BUILD\s+([0-9]+)' ./common/version.h | awk '{print $3}')
        echo "VER=$VERSION_MAJOR.$VERSION_MAJOR.$VERSION_REVISION.$VERSION_BUILD" >> $GITHUB_ENV

    - name: Set outputs Windows
      if: runner.os == 'Windows'
      run: |
        echo "SHORT_SHA=$("${{ github.sha }}".SubString(0, 8))" >> $env:GITHUB_ENV
        $M_MAJ = Select-String -Path ".\common\version.h" -Pattern '#define\s+VERSION_MAJOR\s+(\d+)\s*'
        $M_MIN = Select-String -Path ".\common\version.h" -Pattern '#define\s+VERSION_MINOR\s+(\d+)\s*'
        $M_REV = Select-String -Path ".\common\version.h" -Pattern '#define\s+VERSION_REVISION\s+(\d+)\s*'
        $M_BUILD = Select-String -Path ".\common\version.h" -Pattern '#define\s+VERSION_BUILD\s+(\d+)\s*'
        $VERSION_MAJOR = $M_MAJ.Matches.Groups[1].Value
        $VERSION_MINOR = $M_MIN.Matches.Groups[1].Value
        $VERSION_REVISION = $M_REV.Matches.Groups[1].Value
        $VERSION_BUILD = $M_BUILD.Matches.Groups[1].Value
        echo "VER=$VERSION_MAJOR.$VERSION_MAJOR.$VERSION_REVISION.$VERSION_BUILD" >> $env:GITHUB_ENV


    - name: Set up Linux environment
      if: runner.os == 'Linux'
      run: |
        echo "ROOT_DIR=$(dirname `pwd`)" >> $GITHUB_ENV
        echo "QT_DIR=${{ runner.temp }}/qt-5.6.3-qt-ns-shinked" >> $GITHUB_ENV
        echo "QMAKE=${{ runner.temp }}/qt-5.6.3-qt-ns-shinked/bin/qmake" >> $GITHUB_ENV
        sudo apt-get install -y build-essential curl cmake libgl1-mesa-dev libfontconfig1-dev libdbus-1-dev \
          libx11-dev libxext-dev libxfixes-dev libxi-dev libxrender-dev libxcb1-dev libx11-xcb-dev \
          libxcb-glx0-dev libxcb-keysyms1-dev libxcb-image0-dev libxcb-shm0-dev libxcb-icccm4-dev \
          libxcb-sync-dev libxcb-xfixes0-dev libxcb-shape0-dev libxcb-randr0-dev libxcb-render-util0-dev

    - name: Linux Qt Cache
      if: runner.os == 'Linux'
      uses: actions/cache@v3
      id: linux_qt_cache
      with:
        # maybe we should use some env var for root path?
        path: ${{ runner.temp }}/qt-5.6.3-qt-ns-shinked
        key: linux-qt-patched
    
    - name: Linux, build Qt
      if: runner.os == 'Linux' && steps.linux_qt_cache.outputs.cache-hit != 'true'
      run: |
        pushd "${{ runner.temp }}"
        # curl -L 'https://drive.usercontent.google.com/download?id=1r0BO_prsZXWdmbTMnYDkF3B8zha4L5Ae&export=download&authuser=0&confirm=t&uuid=f6a9b43d-2710-4ea7-a86b-ebc68145ca1b&at=AIrpjvNU3fGsHcjHHGADa0Q2tXUq:1737770748041' -o qt-5.6.3-patched.tar.gz
        curl -L 'https://drive.usercontent.google.com/download?id=14zSGdgn2dQPTYzQO-ukXx9WkDODF-lpK&export=download&authuser=0&confirm=t&uuid=6beaa81f-6cd6-45b0-a269-295dc5f94ee5&at=AIrpjvPNuWytlqeAkSc9hurI3Wez%3A1737807487068' -o qt-5.6.3-qt-ns-shinked.tar.gz
        mkdir qt-5.6.3-qt-ns-shinked && cd qt-5.6.3-qt-ns-shinked
        tar xf ../qt-5.6.3-qt-ns-shinked.tar.gz && rm -f ../qt-5.6.3-qt-ns-shinked.tar.gz
        ls -la 
        #cd build
        #CXXFLAGS="-Wno-deprecated-copy -Wno-int-in-bool-context -Wno-ignored-qualifiers -Wno-class-memaccess -Wno-cast-function-type -Wno-error" \
        #../configure "-nomake" "tests" "-qtnamespace" "QT" "-confirm-license" "-accessibility" "-opensource" "-force-debug-info" "-platform" "linux-g++-64" \
        #"-developer-build" "-fontconfig" "-qt-freetype" "-qt-libpng" "-glib" "-qt-xcb" "-dbus" "-qt-sql-sqlite" "-gtkstyle" "-prefix" "${{ runner.temp }}/qt-5.6.3-patched-qt-ns" -continue -v
        #make -j$(nproc)
        #make install
        popd
        "${{ env.QMAKE }}" -query

    - name: Linux, protobuf cache
      if: runner.os == 'Linux'
      uses: actions/cache@v3
      id: linux_protobuf_cache
      with:
        # maybe we should use some env var for root path?
        path: ${{ env.ROOT_DIR }}/3rdparty/protobuf-3.20.3/dist
        key: linux-protobuf-cache

    - name: Linux, build protobuf
      if: runner.os == 'Linux' && !steps.linux_protobuf_cache.outputs.cache-hit
      run: |
        pushd 3rdparty/protobuf-3.20.3 && mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -Dprotobuf_WITH_ZLIB=NO -Dprotobuf_BUILD_TESTS=NO -Dprotobuf_BUILD_SHARED_LIBS=NO "-DCMAKE_INSTALL_PREFIX=${{ env.ROOT_DIR }}/3rdparty/protobuf-3.20.3/dist" ../cmake
        make -j$(nproc)
        make install

    - name: Linux, Set Up Deps
      if: runner.os == 'Linux'
      env:
        LL_DEPS_P: ${{ secrets.LL_DEPS_P }}
      run: |
        curl https://github.com/a1ext/depz/raw/master/depz.7z -L -o ../depz.7z
        pushd ../
        7z x "-p${{ env.LL_DEPS_P }}" ./depz.7z
        popd
        ln -s "${{ env.ROOT_DIR }}/depz/idasdk90" "${{ env.ROOT_DIR }}/idasdk90"
        ln -s "${{ env.ROOT_DIR }}/depz/idasdk_pro83" "${{ env.ROOT_DIR }}/idasdk_pro83"
        ln -s "${{ env.ROOT_DIR }}/depz/idasdk70" "${{ env.ROOT_DIR }}/idasdk70"
        mkdir -p build

    - name: Linux, build IDA 9 plugin
      if: runner.os == 'Linux'
      run: |
        cd ./build
        "${{ env.QMAKE }}" ../labeless_ida/labeless_ida.pro -spec linux-g++-64 CONFIG+=release TARGET=labeless_ida_90
        /bin/make qmake_all
        
    # - name: Build OllyDBG 1.10 plugin
    #   if: runner.os == 'Windows'
    #   shell: cmd
    #   run: |        
    #     "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" ^
    #     labeless.sln /t:labeless_olly:Rebuild /p:Configuration=Release /p:Platform=Win32 /v:m

    # - name: Build OllyDBG FOFF plugin
    #   if: runner.os == 'Windows'
    #   shell: cmd
    #   run: |        
    #     "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" ^
    #     labeless.sln /t:labeless_olly:Rebuild /p:Configuration=Release_DeFixed /p:Platform=Win32 /v:m

    # - name: Build OllyDBG 2.0 plugin
    #   if: runner.os == 'Windows'
    #   shell: cmd
    #   run: |        
    #     "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" ^
    #     labeless.sln /t:labeless_olly2:Rebuild /p:Configuration=Release /p:Platform=Win32 /v:m

    # - name: Build x64dbg 32-bit plugin
    #   if: runner.os == 'Windows'
    #   shell: cmd
    #   run: |        
    #     "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" ^
    #     labeless.sln /t:labeless_x64dbg:Rebuild /p:Configuration=Release /p:Platform=Win32 /v:m

    # - name: Build x64dbg 64-bit plugin
    #   if: runner.os == 'Windows'
    #   shell: cmd
    #   run: |        
    #     "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" ^
    #     labeless.sln /t:labeless_x64dbg:Rebuild /p:Configuration=Release /p:Platform=x64 /v:m

    - name: Set Up Windows Dependencies
      if: runner.os == 'Windows'
      env:
        LL_DEPS_P: ${{ secrets.LL_DEPS_P }}
      run: |
        curl https://github.com/a1ext/depz/raw/master/depz.7z -L -o C:\depz.7z
        7z x -oc:\ "-p$env:LL_DEPS_P" c:\depz.7z
        New-Item -ItemType Directory -Force -Path c:\depz\idasdk70\plugins
        New-Item -ItemType Directory -Force -Path c:\depz\idasdk_pro83\plugins
        New-Item -ItemType Directory -Force -Path c:\depz\idasdk90sp1\plugins
        Rename-Item -Path "labeless_ida\labeless_ida.vcxproj.user" -NewName "labeless_ida.vcxproj.user_" -Force
        curl -L "https://go.microsoft.com/fwlink/p/?LinkId=323507" -o .\sdksetup.exe
        Start-Process -Wait sdksetup.exe -ArgumentList "/q", "/norestart", "/features", "OptionId.WindowsDesktopSoftwareDevelopmentKit", "OptionId.NetFxSoftwareDevelopmentKit"
 

    # - name: Build IDA 7 plugins
    #   if: runner.os == 'Windows'
    #   shell: cmd
    #   run: |        
    #     "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" ^
    #     labeless.sln /t:labeless_ida:Rebuild /p:Configuration=IDA7 /p:Platform=x64 /v:m /property:QTDIR=c:\depz\qt5.6.0_msvc2015_x64_qt_namespace\qtbase /p:IDA_DIR=c:\depz\idasdk70 /p:SDK_DIR=c:\depz\idasdk70

    #     "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" ^
    #     labeless.sln /t:labeless_ida:Rebuild /p:Configuration=IDA7_x64 /p:Platform=x64 /v:m /property:QTDIR=c:\depz\qt5.6.0_msvc2015_x64_qt_namespace\qtbase /p:IDA_DIR=c:\depz\idasdk70 /p:SDK_DIR=c:\depz\idasdk70
        
    # - name: Build IDA 8 plugins
    #   if: runner.os == 'Windows'
    #   shell: cmd
    #   run: |        
    #     "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" ^
    #     labeless.sln /t:labeless_ida:Rebuild /p:Configuration=IDA8 /p:Platform=x64 /v:m /property:QTDIR=c:\depz\qt5.6.0_msvc2015_x64_qt_namespace\qtbase /p:IDA_DIR=c:\depz\idasdk_pro83 /p:SDK_DIR=c:\depz\idasdk_pro83

    #     "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" ^
    #     labeless.sln /t:labeless_ida:Rebuild /p:Configuration=IDA8_x64 /p:Platform=x64 /v:m /property:QTDIR=c:\depz\qt5.6.0_msvc2015_x64_qt_namespace\qtbase /p:IDA_DIR=c:\depz\idasdk_pro83 /p:SDK_DIR=c:\depz\idasdk_pro83

    # - name: Build IDA 9 plugins
    #   if: runner.os == 'Windows'
    #   shell: cmd
    #   run: |        
    #     "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" ^
    #     labeless.sln /t:labeless_ida:Rebuild /p:Configuration=IDA9_x64 /p:Platform=x64 /v:m /property:QTDIR=c:\depz\qt5.6.0_msvc2015_x64_qt_namespace\qtbase /p:IDA_DIR=c:\depz\idasdk90sp1 /p:SDK_DIR=c:\depz\idasdk90sp1

    # - name: Build Python module sdist
    #   if: runner.os == 'Windows'
    #   shell: cmd
    #   run: |
    #     cd deploy
    #     python.exe -m pip install wheel
    #     python.exe setup.py bdist_wheel

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: labeless_build_${{ env.VER }}_${{ env.SHORT_SHA }}
        path: |
          bin/labeless_olly.dll
          bin/labeless_olly-x86.pdb
          bin/labeless_olly_foff.dll
          bin/labeless_olly_foff-x86.pdb
          bin/labeless_olly2.dll
          bin/labeless_olly2-x86.pdb
          bin/labeless_x64dbg.dp32
          bin/labeless_x64dbg-x86.pdb
          bin/labeless_x64dbg.dp64
          bin/labeless_x64dbg-x64.pdb
          bin/labeless_ida_*.dll
          deploy/dist/*.whl
          bin/labeless_ida_*.pdb
          build/labeless_*.so
